### ISSUE TITLE
(BUG) Samsung Smartthings Button - Wrong Temperature

### ISSUE THREAD

**Issue by CodyRWhite** [tonesto7/homebridge-hubitat-tonesto7#100]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x ] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [ x ] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 2
-  Hubitat App Version: v2.5.8
-  Homebridge Plugin Version: v2.5.8
-  Homebridge Version: v1.3.4
-  NodeJS Version: v14.17.3

## Expected Behavior
**Tell us what you think should be happening**
I would expect Homebridge and HomeKit to match the device temperature. 

## Current Behavior
**What happens instead of the expected behavior?**
Current Device State
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/56890437/126071993-8fcd7040-b5a9-428f-892c-622afdb223eb.png">

HomeKit Sees 
<img width="225" alt="image" src="https://user-images.githubusercontent.com/56890437/126071787-0f43469e-b43e-413d-822e-f605651e3e01.png">

Homebridge Sees
![image](https://user-images.githubusercontent.com/56890437/126071807-6371838a-4092-403c-9bc8-67353f5fa528.png)

Plugin Config 

```
        {
            "name": "Hubitat-v2",
            "app_url_local": "http://x.x.x.x/apps/api/",
            "app_url_cloud": "https://cloud.hubitat.com/api/xxxxxxxxx/apps/",
            "use_cloud": false,
            "app_id": 3,
            "access_token": "xxxxxxxxxxxx",
            "direct_port": 8000,
            "temperature_unit": "C",
            "round_levels": true,
            "adaptive_lighting": true,
            "adaptive_lighting_offset": 0,
            "consider_fan_by_name": true,
            "validateTokenId": true,
            "logConfig": {
                "showChanges": true
            },
            "platform": "Hubitat-v2"
        },
```

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Pair device to Hubitat
2. Add Button to Button Press in Homebridge v2 App on Hubitat
3. Add Button to Button Double Press in Homebridge v2 App on Hubitat
4. Add Button to Button Hold in Homebridge v2 App on Hubitat
5. Add Button to Sensor in Homebridge v2 App on Hubitat

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
N/A

---
Please include a copy of any relevant log output to assist in tracking down the bug
I do not really see anything in the logs that could help, let me know if there is a way to force a log entry for a sensor. I will provide Logs.

**Comment by CodyRWhite** [comment]
Here are the characteristic for that device from the following command in Homebridge I thought it might be helpful.

`[]# curl http://127.0.0.1:51069/accessories`

```
         "aid":11,
         "services":[
            {
               "type":"3E",
               "iid":1,
               "characteristics":[
                  {
                     "type":"14",
                     "iid":2,
                     "perms":[
                        "pw"
                     ],
                     "description":"Identify",
                     "format":"bool"
                  },
                  {
                     "type":"20",
                     "iid":3,
                     "value":"Hubitat-v2",
                     "perms":[
                        "pr"
                     ],
                     "description":"Manufacturer",
                     "format":"string",
                     "maxLen":64
                  },
                  {
                     "type":"21",
                     "iid":4,
                     "value":"Samsung Zigbee Button",
                     "perms":[
                        "pr"
                     ],
                     "description":"Model",
                     "format":"string",
                     "maxLen":64
                  },
                  {
                     "type":"23",
                     "iid":5,
                     "value":"Cody’s Button",
                     "perms":[
                        "pr"
                     ],
                     "description":"Name",
                     "format":"string",
                     "maxLen":64
                  },
                  {
                     "type":"30",
                     "iid":6,
                     "value":"Default-SerialNumber",
                     "perms":[
                        "pr"
                     ],
                     "description":"Serial Number",
                     "format":"string",
                     "maxLen":64
                  },
                  {
                     "type":"52",
                     "iid":7,
                     "value":"1.0.0",
                     "perms":[
                        "pr"
                     ],
                     "description":"Firmware Revision",
                     "format":"string"
                  },
                  {
                     "type":"53",
                     "iid":8,
                     "value":"2.5.8",
                     "perms":[
                        "pr"
                     ],
                     "description":"Hardware Revision",
                     "format":"string"
                  }
               ]
            },
```

**Comment by tonesto7** [comment]
I actually have one of these buttons paired so let me see what I can find.

**Comment by tonesto7** [comment]
I set it up exactly the same as you in the app and everything is working as it should.  The correct temperature is displayed and updating correctly.

Are you running the latest hubitat platform version which will include the latest versions of drivers for this device?

**Comment by CodyRWhite** [comment]
We have actually had this issue since we moved from ST to Hubitat. That said I have rebuilt everything from ground up the other weekend. As of last week everything was on the latest. 

I am still at work right now and don't have access to my boxes but I can get you some specifics later tonight.

**Comment by CodyRWhite** [comment]
Using the default driver in hubitat. The only thing I can think of is Device Firmware. ST used to manage that for me, not sure how to do that on hubitat yet.

**Comment by CodyRWhite** [comment]
Weird I swear I installed this the other night. 

2.2.8.136

I am upgrading to 

2.2.8.138 now

**Comment by CodyRWhite** [comment]
Ok too new versions around 

NodeJS : 14.7.3 - No Change
NPM : 7.20.0 - No Change
Homebridge : 1.3.4 - No Change
Plugin : 2.5.8 -> 2.5.9
App : 2.5.8 -> 2.5.9
Hubitat : 2.2.8.136 -> 2.2.8.138

Opened the app in Hubitat and cycled through the menus Next -> Done. 

I'll stick out tonight and check back in tomorrow if I have any updates. If I see good news sooner i'll throw a comment up.

**Comment by CodyRWhite** [comment]
No change as of this morning.

**Comment by CodyRWhite** [comment]
Update
![image](https://user-images.githubusercontent.com/56890437/126876867-69a15500-c263-4929-9f7b-6bb2b5be0265.png)
![image](https://user-images.githubusercontent.com/56890437/126876882-bfb6b6e2-9766-4f26-984a-900505b0e298.png)


It looks like the app might be pushing the proper value to Homebridge. However Homebridge is no displaying it correctly or pushing it to HomeKit. 

Would you agree?
