### ISSUE TITLE
(BUG) {Incorrect temperature reported in Homekit from temperature sensors} 

### ISSUE THREAD

**Issue by ZaherButt** [tonesto7/homebridge-hubitat-tonesto7#110]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [X ] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 32
-  Hubitat App Version: 1.21
-  Homebridge Plugin Version: v2.5.11
-  Homebridge Version: v1.3.4
-  NodeJS Version: 	v14.17.1

## Expected Behavior
Homekit should display correct temperature from devices.

## Current Behavior
Homekit does not display the correct temperature from devices. Device that have multi sensors, temp and humidity, the humidity reading is correctly displayed, the temperate is not. 
For example my Garage is reporting -6.0 from two temperature sensors when according to homebridge logs and hubitat device info - the temperature should be 21C

## Steps to Reproduce (for bugs)
This is happening on all my Fibaro motion sensors and my Aqara Humidity sensors. 
**Drivers**
Xiaomi Temperature Humidity Sensor
Fibaro Motion Sensor ZW5

## Context
**How has this issue affected you? What are you trying to accomplish?
Siri is unable to tell me the correct temperature for rooms in my house. 

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
Sorry, this has sat so long.  The temperature data reported in the data you shared shows 18C.  So if it's showing -6.0 plugin must think that the temps being sent are in Fahrenheit.
Please check the plugin config to make sure the correct temp unit is being used.
