### ISSUE TITLE
Sensor Not Reporting State Back to Homebridge

### ISSUE THREAD

**Issue by 4thbit** [tonesto7/homebridge-hubitat-tonesto7#112]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ X] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [ X] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 22
-  Hubitat App Version: 2.5.11
-  Homebridge Plugin Version: 2.5.11
-  Homebridge Version: 1.3.4
-  NodeJS Version: v14.17.5

## Expected Behavior
I've added a virtual Garage Door using a Zooz Zen17 and their Virtual Garage Door Code.  The device works properly and garage door operates and is sensed fine using a dashboard.  The device shows properly in the Home app.  I expect it to operate and show current status. 

## Current Behavior
I can only control the device in HomeKit. The sensor never appears to report the state back to homebridge.  Looking at homebridge logs, I see nothing when I close the sensor.  I've also deleted the virtual device entirely and simply setup a simple sensor.  Again, it doesn't seem to send the information to Homekit.  If I go to App Status, the sensor devices are NOT showing up under Event Subscriptions.  

## Steps to Reproduce (for bugs)

1. Add a sensor device (Zen17)
2. Add that sensor to Homebridge V2 app. 
3. Close the sensor and see if there is anything in the homebridge logs at the homebridge server. 

## Context
Just trying to get my garage door to work remotely.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This is almost always because hubitat can't report back to the plugin (Inbound firewall, invalid port, etc).

**Comment by 4thbit** [comment]
Isn't 8000 the only port that is needed? I show it as open.  It's a fresh Ubuntu Server LTS installation with no firewall.
![ports](https://user-images.githubusercontent.com/15252559/131886545-84b68410-626e-418a-a138-9a0fbc5cec5c.png)

**Comment by 4thbit** [comment]
Further... The lighting seems to get pushed properly. I can operate a light switch from the plate on the wall or from hubitat dashboard and I see it in the logs.  My problem only seems to be with sensors.

**Comment by 4thbit** [comment]
No idea what happened but all of a sudden its working and now the Nest is reporting as well.  Hmm...

**Comment by kgustine** [comment]
I just installed homebridge today along with this hubitat app. I am having the exact same issue. All of my lights and fans work great, but the garage feedback and door feedback sensors don’t update 

my garage door is using the zoom garage door app. My door sensors are Aeotec door/window 7 series (4 of them). 

In the hubitat app config I chose them under the sensors category. Maybe that’s the wrong category for a door open/close device?

I hope to experiment more tomorrow.

**Comment by 4thbit** [comment]
I still can't figure out why or what happened but it still appears to be working for me now.  By chance, have you tried to reboot your server that is running homebridge? Not just restart the service but reboot the whole server.

**Comment by kgustine** [comment]
Good call sir! After a reboot everything works flawlessly. Thank you much!

**Comment by 4thbit** [comment]
Sweet! Now I know for sure!
