### ISSUE TITLE
(BUG) Blinds showing as Fan and Sensor in Homebridge/Homekit

### ISSUE THREAD

**Issue by DaveGraham123456** [tonesto7/homebridge-hubitat-tonesto7#114]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [ x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 1
-  Hubitat App Version: 2.5.11
-  Homebridge Plugin Version: 2.5.11
-  Homebridge Version: 1.3.4 (using the UI plugin too)
-  NodeJS Version: 12.18.3

## Expected Behavior
**Tell us what you think should be happening**
Blind in Hubitat is showing as Fan and sensor in Homebridge

## Current Behavior
**What happens instead of the expected behavior?**
To see a blind in homebridge

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

I loaded drivers for ZemiSmart ZigBee  Blind in the Hub
Paired the device, this worked
can press open buttons it in Hubitat and the blind moves 
In Homebridge hubitat, device selection, choose the blind.
About 30 seconds later, a fan and sensor show up.
I unpublish in Hub, go and delete cached accessory in Homebridge, rename the device in Hub, republish.  Same problem but with new name.

## Context
**How has this issue affected you? What are you trying to accomplish?
I experinced the issue, and went to log this ticket, but then realised I didn't ahve OAUTH on.  I went back and did that, but it made no difference.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by DaveGraham123456** [comment]
![Hub-Home3](https://user-images.githubusercontent.com/68233868/132963674-89722598-2271-46dc-b69a-d1c839204e3d.JPG)
![Hub-Home2](https://user-images.githubusercontent.com/68233868/132963675-930ea8ac-e7eb-4c16-9208-a42fee67b75b.JPG)
![Hub-Home1](https://user-images.githubusercontent.com/68233868/132963676-827ff05b-5fba-470f-881e-137f9ea85f01.JPG)
![Hub-Home4](https://user-images.githubusercontent.com/68233868/132963678-4b19b80a-0ef5-4968-8d3f-58810f0ed3df.JPG)
Screen dumps

**Comment by marthoc** [comment]
I have this exact bug also with the ZemiSmart blind. I think it may have something to do with the fact that this device has a speed attribute (you can adjust the speed with which the blind opens/closes) and maybe is being treated a a fan for that reason.

**Comment by marthoc** [comment]
I believe I have tracked this bug to line 110 in HE_ServiceTypes.js: https://github.com/tonesto7/homebridge-hubitat-tonesto7/blob/04aa29aa360e6a58d9f8e8ed7c524012221aa8ad/src/HE_ServiceTypes.js#L110

That line appears to ignore window shades that have a setSpeed or speed characteristic, which this blind does have.

**Comment by tonesto7** [comment]
@marthoc Thanks for looking into this.  I haven't had time recently to review any of these issues. 
I will make some adjustments and get a fix out within the next couple of days.  (Hopefully, today if work doesn't take priority)

**Comment by marthoc** [comment]
@tonesto7 No problem - thanks for taking the time. Much appreciated!

**Comment by tonesto7** [comment]
I just pushed out a quick fix.   Please update the plugin and the app. v2.5.12

**Comment by tonesto7** [comment]
@DaveGraham123456  @marthoc This issue should be resolved.  If it isn't fixed please reopen this issue

**Comment by marthoc** [comment]
@tonesto7 Thanks very much, I have tested and a window shade is now created - a fan accessory is also created which is probably unavoidable (unless you were to tweak the fan service test to exclude the window shade characteristics), but since I can hide these in the Home app I'm not too worried.

**Comment by Helgimagg01** [comment]
Hi, I just installed 5 ZemiSmart blinds motors, and that generated 15 accessories in homebridge, it was no problem to filter the sensors out, but I can find no way to filter out the fans, can you guide me on that as I am maxed out on the number of accessories exposed ?
Thanks in advance
