### ISSUE TITLE
Hubitat Tonesto7 BridgeHubitat-v2WARNINGNOTICE: New version of homebridge-hubitat-tonesto7 available: 2.5.12(BUG) {ENTER TITLE HERE} 

### ISSUE THREAD

**Issue by resgroupmsr** [tonesto7/homebridge-hubitat-tonesto7#121]
Hoobs log shows this:
Hubitat Tonesto7 BridgeHubitat-v2WARNINGNOTICE: New version of homebridge-hubitat-tonesto7 available: 2.5.12
Cannot see any way to update to a 2.5.12 version.  It is updated on Hubitat but Hoobs plugin still showing only 2.5.11 as latest

**Comment by jackflem1** [comment]
I am seeing the same issue - running Hoobs 4.0.104 .

**Comment by tonesto7** [comment]
I'm not sure what to tell you guys.  HOOBS handles plug-ins different. 

It's why I moved over to native Homebridge config-ui-x

It does everything hoobs does and more like splitting off plugins into child bridges which is awesome and prevents plug-ins from slowing down the main bridge

**Comment by jtp10181** [comment]
Might be able to use npm directly to update the plugin? Sorry I have not used HOOBS before but it should have npm in there to run from command line.

If HOOBS installs the plugins globally this should work:
`npm -g update homebridge-hubitat-tonesto7`

Might want to run `npm -g list` first to see what is globally installed, if this plugin is listed you should be able to run the above to re-install / update it

Example of my npm -g list (not hoobs)
![image](https://user-images.githubusercontent.com/99599/135925083-e51feadb-6962-4a89-bd50-4e717c375f07.png)

**Comment by jackflem1** [comment]
that npm ( homebridge-hubitat-tonesto7 ) is not listed on my Hoobs 4.0 system.

**Comment by jtp10181** [comment]
I searched around and HOOBS does not install plugins globally. Not sure what folder they go into. Looks like ~/.hoobs in the home directory of the user it is running as per this post I found about some other plugin. Not sure what user it used but could just poke around in the various /home/ folders to try and find the one with the .hoobs folder? You could replace that last command below with `npm update homebridge-hubitat-tonesto7` and it should update it, if you are in the correct directory. Might have to restart HOOBS after for it to notice the update.

> Log in as the user running HOOBS (HOOBS runs in user mode)
> cd ~/.hoobs/ (You need to be in the directory where HOOBS runs)
> npm install homebridge-homematic@0.1.2 (Don't use a -g)

**Comment by resgroupmsr** [comment]
This plugin was previously Hoobs certified.  Is the response now saying you will not bother with that anymore?

**Comment by tonesto7** [comment]
@resgroupmsr nobody said that!
There is no real change required to work on HOOBS.  All that’s required is a package config file to present plug-in options in the UI

**Comment by resgroupmsr** [comment]
Good news for us who use Hoobs.  Just pointing out that inside Hoobs the only version present is the 2.5.11
![image](https://user-images.githubusercontent.com/57006768/136052815-157101e1-2863-4b70-affb-988777f97b23.png)

**Comment by jackflem1** [comment]
I just switched from Hoobs to native Homebridge config-ui-x.  Problem solved.
