### ISSUE TITLE
(BUG) Running 2.5.14 but HOOBS shows update to 2.5.14 available, won't run

### ISSUE THREAD

**Issue by jacobgraf** [tonesto7/homebridge-hubitat-tonesto7#137]
In HOOBS, I check for updates and it shows an update for this plugin is available to 2.5.14. When I look at the plugin itself, it's already running 2.5.14. I've rebooted HOOBS, the whole machine, I've run all apt updates from the command line and even tried running an npm update. I've even uninstall/reinstalled the plugin, and it still shows an available update to 2.5.14.

Any ideas what might cause this and how to fix it?

Thanks!

**Comment by tonesto7** [comment]
It's so hard to tell. The way hoobs handles npm packages has always been strange. It's like it tries to separate them into a single folder and only keeps one version of a package.  This is why I moved back to native homebridge UI and image, that and many other feature reasons.

Without some sort of package error, I'm not sure how to help with this.
