### ISSUE TITLE
(BUG) HSM triggered Alert being rejected by Homebridge - expected valid finite number and received undefined

### ISSUE THREAD

**Issue by cjattard** [tonesto7/homebridge-hubitat-tonesto7#139]
Running hubitat, communicating with Homebridge docker container.

When HSM detects an intrusion the alert is being detected by the Hubitat Homebridge App in hubitat, however Homebridge is unable to process the alert as it is in a non recognised format - Expected finite number.

As a result the alarm in HomeKit shows the correct mode (Away) but never shows “Triggered”

Supporting photos Attached.
1. From the hubitat app logs
2. From homebridge logs
3. From home App

1.
![C59C6F93-B83E-4A5B-8377-B2D2819B541D](https://user-images.githubusercontent.com/45669214/153638533-daa003be-962f-4837-816d-2e3736b9bdbf.jpeg)

2. 
![359198CE-E51A-4A9D-8B8D-0F7BD8102AA5](https://user-images.githubusercontent.com/45669214/153638563-e927f824-4f2a-428a-a802-d4653e2ea9ac.jpeg)

3. 
![7B712A43-A12B-4338-8DCA-3F419B53B398](https://user-images.githubusercontent.com/45669214/153638612-c5f32ea6-5a74-4d67-87bd-83a92f9fd70c.jpeg)

Thanks

**Comment by cjattard** [comment]
Perhaps something changed since fix release v2.5.7

**Comment by tonesto7** [comment]
Thanks for opening this with so much detail.  Very helpful!
I've been reviewing the code in the plugin and I'm struggling to see why this isn't working currently.  It feels like a bug in Homebridge but I will deconstruct the logic flow more and see if I missed something.
