### ISSUE TITLE
iOS 15.4 and shades

### ISSUE THREAD

**Issue by Drpeppir** [tonesto7/homebridge-hubitat-tonesto7#144]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [ x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?:all 18
-  Hubitat App Version: 2.3.0.124
-  Homebridge Plugin Version:2.5.14
-  Homebridge Version:1.4.0

## Expected Behavior
**Tell us what you think should be happening**
Hey Siri open shade
## Current Behavior
**What happens instead of the expected behavior?**
Shade not supported, have to say set shade to position instead

## Context
**How has this issue affected you? Always What are you trying to accomplish? Simpler shade opening as before
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by dennypage** [comment]
Seeing this as well

**Comment by dennypage** [comment]
This issue was actually a bug in Siri with iOS 15.4, and was addressed today with iOS 15.4.1.

This issue can be closed.
