### ISSUE TITLE
Window Shades/Blinds

### ISSUE THREAD

**Issue by JimPowersDFL** [tonesto7/homebridge-hubitat-tonesto7#159]
**Is your feature request related to a problem? Please describe.**
I have several z-wave blinds connected to my HE hub. In order to be able to specify how far open I want the blinds to be, I had to set up the device as a generic z-wave dimmer. When I used the generic z-wave shade as it originally recognized them as (I'm assuming you are looking for that to make them available as a shade), I was stuck with open and close. As the generic dimmer, I can set where they open or close to manually or with my automations. This also passes to Google Home as a "dimmable light" so I can set the open/close position there as well as in HE.

**Describe the solution you'd like**
I would love to have a way to specify my blinds as window shades for Apple Homekit as well, instead of lights. As of now, Apple Homekit sees them as basic switches so there, I lose the ability to set where they stop. I think a simple fix to allow me to select them as Window Shades would fix the issue, at least I assume it would.

**Describe alternatives you've considered**
I would certainly consider a device type change in HE if that would help but the selection I settled on was suggested by other members of the community. It would have to work for both Google Home AND Apple Homekit.

**Additional context**

**Comment by tonesto7** [comment]
The plugin adds characteristics based on a devices attribututes and capabilities under Hubitat.

Open the Device Debug Data View in Hubitat homebridge app and select one of the blind devices. 
Copy/Paste the output in this issue.
