### ISSUE TITLE
Aeotec MultiSensor 7 as Sensor

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [tonesto7/homebridge-hubitat-tonesto7#162]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is a problem with the buggy Hubitat system, but thought I'd try here first.

I have 3 Aeotec MultiSensor 7 and all of them using the built in driver.

When I want to expose those to HomeKit via your code, they show up under other, not sensors. This seems to make them not work in HomeKit...they sort of work, long delays, inaccurate information, and motion is not useful at all since it comes in 5-10 minutes later.

**Describe the solution you'd like**
I would like Aeotec MultiSensor 7 to appear as a sensor. I have older Aeotec MultiSensor 6 and they work perfectly.

**Comment by tonesto7** [comment]
The plugin adds characteristics based on a devices attribututes and capabilities under Hubitat.  

Open the Device Debug Data View in Hubitat homebridge app and select one of the Multi 7 sensors.  Copy/Paste the output in this issue.
