### ISSUE TITLE
Cannot Change Fan Icon in HomeKit

### ISSUE THREAD

**Issue by rdstov** [tonesto7/homebridge-hubitat-tonesto7#165]
I have found the icon in homekit cannot be changed for a fan associated using Hubitat Homebridge V2. However, other homebridge plugins (such as ecovacs) the fan icon can be changed in homekit. this appears to be an issue with how hubitat homebridge v2 presents a fan to Homebridge/Homekit. Can this be updated to allow for the fan icon to be changed? as i understand it, homekit needs to see as a fanv1 class instead of fan or fanv2 class?

**Comment by tonesto7** [comment]
This is a difficult one.  I looked at allowing FanV1 service but it's too complex for the current structure.  
As much as I would like to allow for changing the icons the v1 service is not as robust to warrant the coding changes required to both the Hubitat app and plugin.

**Comment by rdstov** [comment]
Okay, this is understandable. Is there a way to force the icon from the App side? Something like how you filter capabilities in the app?
