### ISSUE TITLE
(BUG) Advanced Zigbee RGBW Bulb device not reporting correctly

### ISSUE THREAD

**Issue by dougc84** [tonesto7/homebridge-hubitat-tonesto7#166]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: all of them (a few dozen)
-  Hubitat App Version: 2.5.17 (on Hubitat 2.3.3.134)
-  Homebridge Plugin Version: ~2.5.15~ 2.5.18. Issue still persists.
-  Homebridge Version: 1.4.0 (via Hoobs 4.2.2)
-  NodeJS Version: 16.14.0

## Expected Behavior
I have recently added two Zigbee RGB+CCT controllers (generic) to my home setup. When controlling these devices through Hubitat using the recommended **Advanced Zigbee RGBW Bulb** device handler, it updates the `colorMode` to either `CT` to `RGB` depending what setting is used (if a color temperature is set or if a color or hue is set). I expect this value to represent the actual color in Homebridge when in use, and, conversely, reflect the correct value in the Home app.

## Current Behavior
The `CT` value is completely ignored when using a color temperature. Homebridge pulls the RGB color instead.

## Steps to Reproduce (for bugs)
1. Add a device using the **Advanced Zigbee RGBW Bulb** device handler
2. Add that device to Homebridge via the app/integration on Hubitat
3. Ensure a color has been set (using Hubitat) at least one time.
4. Change the bulb to a temperature (in Hubitat).
5. In Hoobs or Homebridge, the color reflected is always the RGB color, not the color temperature.

## Context
I'm just trying to get accurate white color representation out of Homebridge. This works reliably with other RGBW bulbs, like those from Lifx, but not with the **Advanced Zigbee RGBW Bulb** device handler. This makes using these controllers within Homekit unreliable at best.

It seems like this plugin does not properly support the built-in device handler.

---
Please include a copy of any relevant log output to assist in tracking down the bug

I'm happy to provide logs if you tell me which logs you need.

**Comment by nlundquist** [comment]
i have similar behavior when trying to set the color of Phillips Hue bulbs via Homebridge & Hubitat

**Comment by tonesto7** [comment]
Sorry I missed your message 

I've noticed this too.  I'm not sure it's related to homebridge or this plug-in. 
I've noticed this on my native HomeKit Hue bulbs. I will investigate nonetheless
