### ISSUE TITLE
[Feature Request] Refreshing All Device Data frequency

### ISSUE THREAD

**Issue by flesh420x** [tonesto7/homebridge-hubitat-tonesto7#170]
I've been looking for a way to increase the sync of this tool between itself and Hubitat. I noticed in the status of Homebridge that it refreshes all data every 1 hour. So if I add a device from Hubitat to publish to Homebridge it can take up to an hour for it to show up in Homebridge. Yes, you can just restart the service to force the refresh but it would be nice to have an option or config to update to increase the frequency of refresh. See the picture below for the refresh I am referring to.

![image](https://user-images.githubusercontent.com/89482732/208748377-ba5c1fff-8bc7-4f8a-859d-dccf76d848d9.png)

**Comment by tonesto7** [comment]
Hubitat must not be able to talk to your homebridge instance (Obviously homebridge can talk to habitat).  I'm willing to be that the device states are not being reflected correctly in HomeKit (motion, contact, switch, etc.).  
The hub sends the events in realtime to the plugin so it can update Homekit... 

I see 2 issues.  Either you are not pressing done all the way out of the homebridge app in Hubitat or you might need to manually define the IP address of the plugin in the plugin's homebridge config.

The HB Hubitat app is designed to tell the plugin to refresh devices after 10 seconds when the selected devices are changed.

That 1-hour poll is just a way to ensure that the device's states stay in sync.

**Comment by flesh420x** [comment]
Hmmm.. I have done quite a few installs and setups using HOOBS with Hubitat (not plain HB) and never had an issue. Using HB on a setup I did over the weekend it definitely did not update until that hour refresh ran on HB. I can try to define the IP in the plugin's config. Both devices are using static IPs and haven't changed since connection.

**Comment by tonesto7** [comment]
Make sure the port the plugin is using is available as well.
Try defining port 8002 in the plugin config and restart.
I will add some communication tests to the HB Hubitat app and plugin to make it easier to diagnose.

**Comment by flesh420x** [comment]
I will give it a shot. Thank you for the quick responses. All in all they're great apps and I appreciate all the time you spent setting them up.

**Comment by tonesto7** [comment]
We're you able to sort this issue out?

**Comment by flesh420x** [comment]
I was. Thank you! I opened up comms between devices and things started working fine. First time I had that issue. Not so sure what was different, but it works. And the check comms you put in was helpful. Thank you for that.
