### ISSUE TITLE
bug about Thermostat Sinope TH1124ZB

### ISSUE THREAD

**Issue by hardlock75** [tonesto7/homebridge-hubitat-tonesto7#192]
i have only heater thermostats, but in Homekit i see cold option.. i put thermostats on "Remove Capabilities from Thermostats" 

<img width="388" alt="Capture d’écran, le 2023-06-29 à 11 39 04" src="https://github.com/tonesto7/homebridge-hubitat-tonesto7/assets/58529389/b625ed25-6858-41a5-ab71-31df3add18e4">

<img width="406" alt="Capture d’écran, le 2023-06-29 à 11 40 20" src="https://github.com/tonesto7/homebridge-hubitat-tonesto7/assets/58529389/baf5a71c-91be-48e8-88a5-d518492c34d5">

there is the device data
{
    "name": "Chambre Nathan TH1124ZB",
    "basename": "Sinope TH1124ZB (4KW) Thermostat",
    "deviceid": "19",
    "status": "ACTIVE",
    "manufacturer": "Unknown",
    "model": "Thermostat TH112xZB with energy meter",
    "deviceNetworkId": "5F43",
    "lastActivity": "2023-06-29T15:44:52+0000",
    "capabilities": [
        "Configuration",
        "EnergyMeter",
        "Lock",
        "Notification",
        "PowerMeter",
        "Refresh",
        "TemperatureMeasurement",
        "Thermostat"
    ],
    "capabilities_processed": {
        "Notification": 1,
        "Refresh": 1,
        "TemperatureMeasurement": 1,
        "Thermostat": 1,
        "ThermostatOperatingState": 1
    },
    "capabilities_filtered": [
        "ThermostatFanMode",
        "Lock",
        "ThermostatCoolingSetpoint"
    ],
    "commands": [
        "auto",
        "configure",
        "cool",
        "deviceNotification",
        "displayAdaptive",
        "displayOff",
        "displayOn",
        "emergencyHeat",
        "fanAuto",
        "fanCirculate",
        "fanOn",
        "heat",
        "lock",
        "off",
        "refresh",
        "refreshTemp",
        "refreshTime",
        "resetDailyEnergy",
        "resetEnergyOffset",
        "resetMonthlyEnergy",
        "resetWeeklyEnergy",
        "resetYearlyEnergy",
        "setClockTime",
        "setCoolingSetpoint",
        "setHeatingSetpoint",
        "setThermostatFanMode",
        "setThermostatMode",
        "unlock"
    ],
    "commands_processed": {
        "deviceNotification": 1,
        "displayAdaptive": 1,
        "displayOff": 1,
        "displayOn": 1,
        "lock": 1,
        "off": 1,
        "refreshTemp": 1,
        "refreshTime": 1,
        "resetDailyEnergy": 1,
        "resetEnergyOffset": 1,
        "resetMonthlyEnergy": 1,
        "resetWeeklyEnergy": 1,
        "resetYearlyEnergy": 1,
        "setClockTime": 1,
        "setHeatingSetpoint": 1,
        "unlock": 1
    },
    "customflags": {
        
    },
    "attributes": {
        "coolingSetpoint": 30,
        "cost": 478.05,
        "dailyCost": 0.0,
        "dailyEnergy": 0.0,
        "energy": 5096.479,
        "heatingDemand": 0,
        "heatingSetpoint": 16,
        "lock": "unlocked ",
        "maxPower": 931,
        "monthlyCost": 0.0,
        "monthlyEnergy": 0.0,
        "outdoorTemp": 20.6,
        "power": 0,
        "supportedThermostatFanModes": "[\"auto\"]",
        "supportedThermostatModes": "[\"off\", \"heat\"]",
        "temperature": 23.15,
        "thermostatFanMode": "auto",
        "thermostatMode": "heat",
        "thermostatOperatingState": "idle",
        "thermostatSetpoint": 16,
        "weeklyCost": 0.0,
        "weeklyEnergy": 0.0,
        "yearlyCost": 0.0,
        "yearlyEnergy": 0.0
    },
    "attributes_processed": {
        "cost": 478.05,
        "dailyCost": 0.0,
        "dailyEnergy": 0.0,
        "heatingDemand": 0,
        "heatingSetpoint": 16,
        "lock": "unlocked ",
        "maxPower": 931,
        "monthlyCost": 0.0,
        "monthlyEnergy": 0.0,
        "outdoorTemp": 20.6,
        "temperature": 23.15,
        "thermostatOperatingState": "idle",
        "thermostatSetpoint": 16,
        "weeklyCost": 0.0,
        "weeklyEnergy": 0.0,
        "yearlyCost": 0.0,
        "yearlyEnergy": 0.0
    },
    "eventHistory": [
        "2023-06-29 11:39:34.695 | [temperature] | (23.15)",
        "2023-06-29 11:32:45.417 | [command-setThermostatMode] | (null)",
        "2023-06-29 11:32:43.667 | [command-setThermostatMode] | (null)",
        "2023-06-29 11:32:40.064 | [command-setThermostatMode] | (null)",
        "2023-06-29 11:32:38.792 | [command-setHeatingSetpoint] | (null)",
        "2023-06-29 11:32:35.489 | [command-setThermostatMode] | (null)",
        "2023-06-29 11:32:30.567 | [command-setCoolingSetpoint] | (null)",
        "2023-06-29 11:32:28.978 | [command-setThermostatMode] | (null)",
        "2023-06-29 11:29:54.634 | [temperature] | (23.09)",
        "2023-06-29 11:20:14.571 | [temperature] | (22.98)",
        "2023-06-29 11:10:34.502 | [temperature] | (22.7)",
        "2023-06-29 11:05:02.32 | [outdoorTemp] | (20.6 C)",
        "2023-06-29 11:05:02.34 | [command-deviceNotification] | (null)",
        "2023-06-29 11:00:54.356 | [temperature] | (22.56)",
        "2023-06-29 10:54:46.85 | [temperature] | (22.03)",
        "2023-06-29 10:51:37.798 | [temperature] | (21.53)",
        "2023-06-29 10:32:23.599 | [temperature] | (21.01)",
        "2023-06-29 10:22:43.544 | [temperature] | (21)",
        "2023-06-29 10:13:03.57 | [temperature] | (20.99)",
        "2023-06-29 10:05:02.523 | [outdoorTemp] | (18.1 C)"
    ]
}
--------------
Thank you

**Comment by tonesto7** [comment]
This is a bug in HomeKit... I've spent a great deal of time trying to filter out devices that only have cool or hot

**Comment by hardlock75** [comment]
I am a old user, of homebridge-smartthings and I migrated to hubitat. Thank you anyway, I love your work.
