### ISSUE TITLE
Getting "{"error":"Permission denied"}" when trying to get Plug-In Configuration Data

### ISSUE THREAD

**Issue by tsviper** [tonesto7/homebridge-hubitat-tonesto7#2]
Just updated to your latest release and how nothing is working and I'm getting this error when selecting the Plugin Config Button in the app in Hubitat.

{"error":"Permission denied"}

Also seeing this in the Homebridge logs:
"[10/8/2018, 2:51:01 PM] [Hubitat] Direct Connect Is Listening On 10.0.0.79:8000
error at req:  write EPROTO 1995477520:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:"

**Comment by seannymurrs** [comment]
Same error here

**Comment by mixanik78** [comment]
and here
