### ISSUE TITLE
update breaks homebridge-hubitat

### ISSUE THREAD

**Issue by HiddenLca** [tonesto7/homebridge-hubitat-tonesto7#20]
The new 2.0 homebridge-hubitat-tonesto7 plugin appears to require information not available in hubitat configuration such as "App-ID":

App ID *
To get this information, open Homebridge (Hubitat) App, and tap on 'View Configuration Data for Homebridge'

This information is not available on hubitat. 

on homebridge: 
Homebridge (Hubitat)
Copyright© 2018 Anthony Santilli
Version: 1.5.2

**Comment by apwelsh** [comment]
You can get the app ID n Hubitat from the URL. It is the number at, or near the end of the URL.

Ex: 896 in my case...
![D5BDCE34-CCF0-43D3-BC68-923556228A28](https://user-images.githubusercontent.com/15111403/97119429-5ed42400-16cd-11eb-8ecf-01bfd0b86790.jpeg)

**Comment by HiddenLca** [comment]
Thanks, will try that!
