### ISSUE TITLE
Mapping of certain HomeKit variables.

### ISSUE THREAD

**Issue by RadDip** [tonesto7/homebridge-hubitat-tonesto7#200]
**Is your feature request related to a problem? Please describe.**
Hello:

Is there a way to map certain variables to HomeKit entities?

For example I have the new IKEA Vindstryka Zigbee air quality sensor that is linked to my Hubitat via a custom device driver. The driver shows the temp, humidity, airqualityindex, airqualitylevel and pm25 in hubitat. However only the temp and humidity are showing up in HomeKit

Thank you

**Comment by tonesto7** [comment]
Please open the Hubitat Homebridge app > go to device debug & history > select the device > copy and paste the json data output here

**Comment by RadDip** [comment]
As per your request, please see below

{
    "name": "Ikea Air Quality Sensor Living Room",
    "basename": "VINDSTYRKA Air Quality Monitor",
    "deviceid": "563",
    "status": "ACTIVE",
    "manufacturer": "Unknown",
    "model": "VINDSTYRKA Air Quality Monitor",
    "deviceNetworkId": "8C5F",
    "lastActivity": "2023-08-28T12:08:26+0000",
    "capabilities": [
        "Actuator",
        "AirQuality",
        "Configuration",
        "HealthCheck",
        "Refresh",
        "RelativeHumidityMeasurement",
        "TemperatureMeasurement"
    ],
    "capabilities_processed": {
        "Actuator": 1,
        "Configuration": 1,
        "Refresh": 1,
        "RelativeHumidityMeasurement": 1,
        "TemperatureMeasurement": 1
    },
    "capabilities_filtered": [
        
    ],
    "commands": [
        "configure",
        "initialize",
        "ping",
        "refresh"
    ],
    "commands_processed": {
        
    },
    "commands_filtered": [
        "configure",
        "initialize",
        "ping",
        "refresh"
    ],
    "customflags": {
        
    },
    "attributes": {
        "airQualityIndex": 71,
        "airQualityLevel": "Moderate",
        "checkInterval": null,
        "healthStatus": "online",
        "humidity": 50,
        "pm25": 1,
        "rtt": 170,
        "temperature": 77
    },
    "attributes_processed": {
        "temperature": 77
    },
    "attributes_filtered": [
        "humidity",
        "airQualityLevel",
        "pm25",
        "airQualityIndex",
        "checkInterval",
        "rtt",
        "healthStatus"
    ],
    "eventHistory": [
        "2023-08-28 08:08:26.526 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:08:24.741 | [humidity] | (50 % RH)",
        "2023-08-28 08:07:56.554 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:06:56.656 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:06:48.238 | [temperature] | (77 \u00b0F)",
        "2023-08-28 08:06:26.771 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:05:37.106 | [airQualityIndex] | (71)",
        "2023-08-28 08:05:26.882 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:04:27.092 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:03:25.553 | [humidity] | (51 % RH)",
        "2023-08-28 08:03:08.959 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:02:09.102 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:01:49.013 | [temperature] | (77 \u00b0F)",
        "2023-08-28 08:01:09.272 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 08:00:39.323 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 07:59:35.291 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 07:58:35.435 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 07:58:26.477 | [humidity] | (51 % RH)",
        "2023-08-28 07:57:35.579 | [pm25] | (1 \u03bcg/m3)",
        "2023-08-28 07:56:49.697 | [temperature] | (77 \u00b0F)"
    ]
}

**Comment by tonesto7** [comment]
Sorry i missed this...  I'm working on adding air quality support right now

**Comment by RadDip** [comment]
No problem.  Awesome!   Thank you!

**Comment by tonesto7** [comment]
Just pushed out a new version of the app and plugin... In my testing it now supports basic support for  Air Quality
