### ISSUE TITLE
Homekit Window Shade Positioning

### ISSUE THREAD

**Issue by RadDip** [tonesto7/homebridge-hubitat-tonesto7#201]
## Collect Device Debug Data
    
MetaData:
DisplayName: Bedroom Left Shade
BaseName: Generic Z-Wave Shade
DeviceID: 139
Status: ACTIVE
Manufacturer: Unknown
Model: Generic Z-Wave Shade
DeviceNetworkId: 15
LastActivity: 2023-08-28 11:53:43+0000

Attributes:
 • battery: 100 (Allowed)
 • position: 44 (Filtered)
 • switch: on (Allowed)
 • windowShade: partially open (Allowed)

Capabilities:
 • Actuator (Allowed)
 • Battery (Allowed)
 • Configuration (Allowed)
 • Refresh (Allowed)
 • Switch (Allowed)
 • WindowShade (Allowed)

Commands:
 • close (Allowed)
 • configure (Filtered)
 • off (Allowed)
 • on (Allowed)
 • open (Allowed)
 • refresh (Filtered)
 • setPosition (Allowed)
 • startPositionChange (Filtered)
 • stopPositionChange (Filtered)

Event History:
 • 2023-08-28 07:18:36.722 | [battery] | (100 %)
 • 2023-08-28 07:18:36.78 | [windowShade] | (opening)
 • 2023-08-28 07:18:36.875 | [command-setPosition] | (null)
 • 2023-08-28 07:18:36.978 | [windowShade] | (partially open)
 • 2023-08-28 07:18:37.014 | [windowShade] | (opening)
 • 2023-08-28 07:18:37.09 | [command-setPosition] | (null)
 • 2023-08-28 07:18:37.178 | [battery] | (100 %)
 • 2023-08-28 07:18:37.554 | [command-setPosition] | (null)
 • 2023-08-28 07:18:37.694 | [windowShade] | (partially open)
 • 2023-08-28 07:18:37.861 | [battery] | (100 %)
 • 2023-08-28 07:18:37.926 | [windowShade] | (opening)
 • 2023-08-28 07:18:37.962 | [command-setPosition] | (null)
 • 2023-08-28 07:18:38.07 | [windowShade] | (partially open)
 • 2023-08-28 07:18:38.27 | [battery] | (100 %)
 • 2023-08-28 07:18:43.569 | [position] | (44 %)
 • 2023-08-28 07:30:00.248 | [windowShade] | (opening)
 • 2023-08-28 07:30:00.392 | [command-setPosition] | (null)
 • 2023-08-28 07:30:01.978 | [windowShade] | (partially open)
 • 2023-08-28 07:30:02.063 | [battery] | (100 %)
 • 2023-08-28 07:53:43.978 | [battery] | (100 %)

## Issue Description

  - What issue are you experiencing?  I have (3) window shades of identical ilk as listed above.  Their status in homekit no longer shows for the respective devices.  It only shows "opening" or "closing" with a spinning wheel.   As a matter of fact this is the error that shows up in my hoobs log "ERRORError getting value for Characteristic [Current Position] Using Attribute (position) for Bedroom Left Shade (Bedroom Left Shade)".   This seemed to start to happen with the latest V2.9 update

  - What is the expected behavior?  Accurate representation of shade position in homekit
  - What is the current behavior? Shows device "opening" or "closing" with spinning wheel
  - What are the steps to reproduce?  Just looking homekit app and status of shades
  - What version of the plugin are you using? V2.9
  - Is this device using a custom driver or builtin hubitat driver? No
  - What version of the Homebridge Hubitat app are you using? V2.9

Also on iOS 16.6.  Rebooted all homekit hubs, hubitat hub and hoobs hub several times.
  
<img width="322" alt="Screenshot 2023-08-28 at 8 32 47 AM" src="https://github.com/tonesto7/homebridge-hubitat-tonesto7/assets/70068700/d98baad0-b928-4635-a04c-3e0bcfe51ecc">
<img width="322" alt="Screenshot 2023-08-28 at 8 32 47 AM" src="https://github.com/tonesto7/homebridge-hubitat-tonesto7/assets/70068700/e027bea3-1579-40ae-a7c8-7ce8739487b1">

**Comment by ppkhoa** [comment]
I encounter the same issue, same error message in the logs about undefined position value. This started happening after updating to plugin version 2.9. 

Functionality-wise, I can still control the shade (mine is Aqara E3 Zigbee shade roller motor). If I set position via Home app, it will display that position. If I change the shade position via other means (manually or via Hubitat), Home app does not update position value. When I check the position in Home app, there’s a spinning wheel next to the old position value and error message in Homebridge logs about undefined position value

![image](https://github.com/tonesto7/homebridge-hubitat-tonesto7/assets/6913552/b2e70775-1416-4349-8c97-2d1073d6e177)

**Comment by DrFunkelstein** [comment]
I'm having the exact same bug with my z-wave shades.

**Comment by RadDip** [comment]
Also noticed that all my Zigbee temp sensors that also have humidity built in, no longer display humidity.

As a test,I enabled both my shades and temp sensors in the newly built in HomeKit capability in Hubitat.  They all show up and display properly.

Would prefer though to continue to utilize your app and its functionality due to its much greater flexibility and power.

Would very much appreciate you addressing these issues soon considering all the effort you spent in v2.9 to provide the functionality directly in the app to initiate and send bug issues and enhancements.  Assumed this capability was meant to address such issues quicker.

Thank you for all your efforts.

**Comment by tonesto7** [comment]
@DrFunkelstein @RadDip 

I will look into this.  I don't have my shades under Hubitat so I never noticed any issues.

**Comment by tonesto7** [comment]
I see the issue.  
If you look at the data provided the position attribute is being filtered out,  that's what is happening to humidity in my test here.  
Now I need to figure out why and get you a fix out this afternoon!

**Comment by RadDip** [comment]
Thank you very much Tonesto7.  I really appreciate you looking into this.

Also curious on the HomeKit mapping I posted in the enhancement section.   But I understand if this will take some time to look into and perhaps if possible show up in a future version.

Thanks again for all your efforts and great app!

**Comment by tonesto7** [comment]
@RadDip @DrFunkelstein Just pushed out a new release of both the app and plugin to resolve the humidity and hopefully the windowShade stuff.

**Comment by RadDip** [comment]
All appears to be working well.  Thank you very much Tonesto7.  Very much appreciated.

**Comment by DrFunkelstein** [comment]
Awesome, mine's working with the updates as well, thanks!!
