### ISSUE TITLE
Garage Door Opening does not fire off notification on V 2.90 and greater

### ISSUE THREAD

**Issue by speedracercjr** [tonesto7/homebridge-hubitat-tonesto7#203]
-  [ X] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [X ] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 
-  Hubitat App Version: 2.9.1
-  Homebridge Plugin Version: 2.9.2 (But 2.8.3 works)
-  Homebridge Version: 1.6.1
-  NodeJS Version: 18
![Not worksing screenshot](https://github.com/tonesto7/homebridge-hubitat-tonesto7/assets/44625678/7df62482-09d6-444f-acbc-2e91e0787c7e)

## Expected Behavior
On Homebridge version 2.8.3 or earlier I was getting notifications via the Home app on my iPhone of the garage door opening or closing.  With version 2.90, 2.91 & 2,92 those notification no longer seem to work.  If I install back to 2.8.3 on Homebridge everything works fine again.

## Current Behavior
While the garage doors do open if I use the Home app on my iPhone no notification shows up of the open or closed status.

## Steps to Reproduce (for bugs)

1. Open or Close the garage either via a physical button, or via the Home app on the iPhone
2. No notification shows up 

---
{
    "name": "Big Garage Door",
    "basename": "Big Garage Door",
    "deviceid": "696",
    "status": "ACTIVE",
    "manufacturer": "Unknown",
    "model": "Zooz Garage Door",
    "deviceNetworkId": "747-door",
    "lastActivity": "2023-09-09T20:14:27+0000",
    "capabilities": [
        "Actuator",
        "ContactSensor",
        "DoorControl",
        "GarageDoorControl",
        "Refresh",
        "Sensor"
    ],
    "capabilities_processed": {
        "Actuator": 1,
        "ContactSensor": 1,
        "DoorControl": 1,
        "GarageDoorControl": 1,
        "Refresh": 1,
        "Sensor": 1
    },
    "capabilities_filtered": [
        
    ],
    "commands": [
        "close",
        "open",
        "refresh"
    ],
    "commands_processed": {
        "close": 1,
        "open": 1
    },
    "commands_filtered": [
        "refresh"
    ],
    "customflags": {
        
    },
    "attributes": {
        "contact": "closed",
        "door": "closed"
    },
    "attributes_processed": {
        "contact": "closed",
        "door": "closed"
    },
    "attributes_filtered": [
        
    ],
    "eventHistory": [
        "2023-09-09 15:14:27.361 | [contact] | (closed)",
        "2023-09-09 15:14:27.355 | [door] | (closed)",
        "2023-09-09 15:14:17.08 | [door] | (closing)",
        "2023-09-09 15:12:48.169 | [contact] | (open)",
        "2023-09-09 15:12:48.161 | [door] | (open)",
        "2023-09-09 15:12:32.914 | [command-open] | (null)",
        "2023-09-09 15:12:32.815 | [door] | (opening)",
        "2023-09-09 15:12:23.831 | [contact] | (closed)",
        "2023-09-09 15:12:23.826 | [door] | (closed)",
        "2023-09-09 15:12:13.327 | [command-close] | (null)",
        "2023-09-09 15:12:13.248 | [door] | (closing)",
        "2023-09-09 15:11:55.407 | [contact] | (open)",
        "2023-09-09 15:11:55.401 | [door] | (open)",
        "2023-09-09 15:11:39.999 | [command-open] | (null)",
        "2023-09-09 15:11:39.695 | [door] | (opening)",
        "2023-09-09 15:00:59.991 | [contact] | (closed)",
        "2023-09-09 15:00:59.985 | [door] | (closed)",
        "2023-09-09 15:00:49.696 | [door] | (closing)",
        "2023-09-09 14:59:06.588 | [contact] | (open)",
        "2023-09-09 14:59:06.582 | [door] | (open)"
    ]
}

**Comment by ZeroBright** [comment]
Noticed the same behavior for any lock / garage as well. Works one time after a restart then does not provide notifications or updates. Restoring to 2.8.3 returns to normal

**Comment by chaselampley** [comment]
I am also having this issue but it is extended to devices that are manually updated. If I turn a switch on manually it reflects in homebridge but not in homekit. Rolling back to 2.8.3 resolved my issues.

**Comment by evlnte** [comment]
I am also experiencing significant delays in HomeKit for Lock and Open-close Sensor events logged accurately in Hubitat. The logs shows precisely when the event trigger occurs, but the Homekit notification can occur minutes to as much as 10+ minutes later than the actual event was logged in Hubitat.

**Comment by tonesto7** [comment]
Thanks for sharing this!  Sorry I haven't replied sooner.  I will review the changes I made between 2.8.3 and the latest release and provide a fix.  

I worry though that the issue might be with recent changes in HomeKit which will require Apple update to fix

**Comment by tonesto7** [comment]
> I am also experiencing significant delays in HomeKit for Lock and Open-close Sensor events logged accurately in Hubitat. The logs shows precisely when the event trigger occurs, but the Homekit notification can occur minutes to as much as 10+ minutes later than the actual event was logged in Hubitat.

I have been noticing this lately with many notifications (not just HomeKit)

**Comment by tonesto7** [comment]
I've reviewed the code, and I didn't change anything that would affect you... I honestly think this is a HomeKit issue (locally) 
Not sure what homekit hub devices (apple tv's, homepods) you have but it might be a good idea to reboot all of them

**Comment by speedracercjr** [comment]
Will give that a spin, everything is getting updated with the new OS's that came out.  Will report back with hopefully better results.

**Comment by jtp10181** [comment]
This is happening for multiple people as posted in the forums. Here is the errors from my Homebridge logs below.
My Forums post: https://community.hubitat.com/t/release-homebridge-hubitat-v2-0/54056/1213?u=jtp10181

Seems like the same issue for everyone and has occurred since the 2.9.x updates as OP stated.

```
change: {
  deviceid: '334',
  attribute: 'door',
  value: 'opening',
  data: null,
  date: '2023-09-19T19:12:01+0000'
}
char:  {
  format: 'uint8',
  perms: [ 'ev', 'pr' ],
  minValue: 0,
  maxValue: 4,
  minStep: 1,
  validValues: [ 0, 1, 2, 3, 4 ]
}
[9/19/2023, 2:12:00 PM] [Hubitat-v2] [Garage Door] Attribute (door) | OldValue: closed | NewValueIn: [opening] | NewValueOut: [undefined] | Characteristic: (Current Door State
[9/19/2023, 2:12:00 PM] [Hubitat-v2] [Device Event]: (Garage Door) [DOOR] is opening
[9/19/2023, 2:12:14 PM] [Hubitat-v2] [Device Event]: (Garage Door) [DOOR] is open
[9/19/2023, 2:12:14 PM] [Hubitat-v2] [Device Event]: (Garage Door) [CONTACT] is open
[9/19/2023, 2:12:34 PM] [Hubitat-v2] [Device Event]: (Family Room Sensor) [MOTION] is inactive
change: {
  deviceid: '334',
  attribute: 'door',
  value: 'closing',
  data: null,
  date: '2023-09-19T19:12:36+0000'
}
char:  {
  format: 'uint8',
  perms: [ 'ev', 'pr' ],
  minValue: 0,
  maxValue: 4,
  minStep: 1,
  validValues: [ 0, 1, 2, 3, 4 ]
}
[9/19/2023, 2:12:35 PM] [Hubitat-v2] [Garage Door] Attribute (door) | OldValue: open | NewValueIn: [closing] | NewValueOut: [undefined] | Characteristic: (Current Door State
[9/19/2023, 2:12:35 PM] [Hubitat-v2] [Device Event]: (Garage Door) [DOOR] is closing
[9/19/2023, 2:12:38 PM] [Hubitat-v2] Error getting value for Characteristic [Current Door State] Using Attribute (door) for Garage Door (Garage Door)
[9/19/2023, 2:12:38 PM] [homebridge-hubitat-tonesto7] This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
```

**Comment by tonesto7** [comment]
I promise to set aside time tomorrow to investigate this

**Comment by jtp10181** [comment]
https://github.com/tonesto7/homebridge-hubitat-tonesto7/commit/d2f3e46c546038163ba14368a9e66872f9344521 v2.9.3 of the HB plugin did the trick for me. Thanks! Working as expected again.

**Comment by evlnte** [comment]
I am not seeing an improvement on the status changes from Hubitat. While I see the changes occur in Hubitat, door open/close changes take several minutes to appear in Home app; if at all. Updating to iOS 17 had no effect.

**Comment by speedracercjr** [comment]
Thanks @tonesto7 for the quick fix, confirmed the updates fixed the issue!
