### ISSUE TITLE
[Feature Request] Remove 'Fan' capability from Thermostat (UK)

### ISSUE THREAD

**Issue by mayhew132** [tonesto7/homebridge-hubitat-tonesto7#30]
In the UK we typically don't have 'air conditioning' based heating systems, at the moment when integrating a Thermostat into HomeKit 2 types of devices are added, a thermostat and a fan. This seems to only apply to the Hubitat integration, not the ST integration.

It would be great if there was an option to remove the 'fan' capability from any Hubitat thermostats integrated into HomeKit via this Homebridge plugin (similar to how we can select 'Heat only' thermostats).

**Comment by tonesto7** [comment]
You're right... I thought about this after I added it.  I will move the thermostat + fan into a separate input.
This will be available in the next release

**Comment by mayhew132** [comment]
Thanks Anthony - keep up the good work :)

**Comment by tonesto7** [comment]
v2.1.2+ Added a separate input to show the thermostat with fan.  The default input does not show it any more

**Comment by mayhew132** [comment]
Hi Anthony - I noticed that if I still use the 'Heat Only' thermostats category it still seems to apply a fan onto these devices (if I use the top one 'Thermostats' - it doesn't). 

The thermostats i'm trying to add are all underfloor heating controllers so will be 'heat-only':

<img width="888" alt="image" src="https://user-images.githubusercontent.com/25966969/99095669-559fee00-25cd-11eb-8160-cb7637a9da01.png">

Any chance of being able to apply the same as what was introduced for the top category to the 'Heat Only' ones please?

Cheers
Guy
