### ISSUE TITLE
Ability to rename the Homebridge app after installation

### ISSUE THREAD

**Issue by rakgupta** [tonesto7/homebridge-hubitat-tonesto7#35]
**Is your feature request related to a problem? Please describe.**
I installed the app in Hubitat with the default name (Homebridge v2). After I had configured it, I wanted to change the name to something more descriptive (e.g. Homebridge - Dev) but I cannot rename the app. Another reason for re-naming was that I was going to switch from MakerAPI to the app and I have 2 instances of Homebridge running (Prod and Dev), so I wanted to be able to differentiate between the two (they will have different devices being exposed).

**Describe the solution you'd like**
User should be able to rename the app

**Describe alternatives you've considered**
Deleting the app and then reconfiguring it. Since this is a development instance of the app, it's not a big deal but if I had configured it with all devices, it would have been a pain to delete and reconfigure.

**Additional context**

**Comment by tonesto7** [comment]
You can rename the instance.  It's at the bottom of the main page

**Comment by rakgupta** [comment]
Ah - sorry I missed that! Clouting the issue now
