### ISSUE TITLE
Hubitat App Error: java.lang.Exception: No response data exists for async request on line 1264 (asyncHttpCmdResp)

### ISSUE THREAD

**Issue by kleynhae** [tonesto7/homebridge-hubitat-tonesto7#36]
After updating to the latest version, the below error started popping up
java.lang.Exception: No response data exists for async request on line 1264 (asyncHttpCmdResp)

**Comment by kleynhae** [comment]
Thanks for adding more awesome features. I'm on V2.1.6 and 2.1.3 for the plugin. I'm unfortunately still getting the below message
java.lang.Exception: No response data exists for async request on line 1295 (asyncHttpCmdResp)

**Comment by edasque** [comment]
I am seeing the same thing, with the port for the plugin set to 8000

**Comment by tonesto7** [comment]
This issue should be resolved in the latest release.  Please reopen if it occurs again
