### ISSUE TITLE
Hubitat-v2 Plugin is not Configured | Skipping...

### ISSUE THREAD

**Issue by BUMPRW** [tonesto7/homebridge-hubitat-tonesto7#39]
I've configured it on both sides, loaded, reloaded, reconfigured, and repeated the process several times.

11/20/2020, 8:16:30 AM > [11/20/2020, 8:16:30 AM] [Hubitat-v2] Hubitat-v2 Plugin is not Configured | Skipping...
11/20/2020, 8:16:30 AM > [11/20/2020, 8:16:30 AM] Loading 1 accessories...

I'm new to the version, but I've never had a problem with earlier versions

latest errors noted in hubitat token, ap id, and IP address are XXXX for security purposes:

app:912020-11-20 15:13:28.721 errorHomebridge (v2.1.6) | sendHttpPost: no plugin server configured src: sendDeviceRefreshCmd   path: refreshDevices   [app_id:xx, access_token:xxxxxxxxxxxxxxxxx]

app:912020-11-20 15:13:25.710 errorHomebridge (v2.1.6) | sendHttpPost: no plugin server configured src: updateServicePrefs   path: updateprefs   [app_id:xx, access_token:xxxxxxxxxxxxxxxxx, use_cloud:false, validateTokenId:false, local_hub_ip:xxx.xxx.xxx.xxx]

Update 2020-11-20 19:16 (US CST) Just ran a test Firewalls off, with all ports from the computer on which Homebridge resides monitored, nothing from Homebridge-hubitat is going out to query the hubitat, so it is not a firewall issue, or router issue.  All other communications from Homebridge to hubitat appear to be operating normally.  

Update 2020-11-22 17:03 (US CST) Same results running on another computer, but same hubitat.  Your Smartings plug-in is still working fine

FIXED using Chrome vs. Safari Browser copy and paste functions.

**Comment by tonesto7** [comment]
Try to copy/paste the config generated by the app into the platform section of the homebridge config.json.

**Comment by BUMPRW** [comment]
That was the last thing I tried, since it appears that “Hubitat Package Manager” injects changes in title to Hombridge v2’.  I thought that might be causing it not to identify the app.  Prior to this version I was using port 8005 to ensure I didn’t interfere with Smarthings.  I haven’t found a way to make that change to see if it makes a difference.  I can obviously make the change on one side, but not the other. I also use your Smarthings app which is working fine.

**Comment by BUMPRW** [comment]
Just tried it again.  I noted the version now is 2.16.  Internally it says 2.15.   I probably need to ensure the versions match, but I didn’t try that. I also noted previously the log preferences didn’t match and in configuration I aligned them to Homebridge, I haven’t repeated that step in three or four tries.  Currently, all that I am changing in the Homebridge config are url, app id, and app token.  Then I’m restarting and I get the same error.  I’ll try matching the version in hubitat.

**Comment by BUMPRW** [comment]
I currently access my hubitat through http.  I have not setup https.  Could that be the issue?

**Comment by BUMPRW** [comment]
Fix was as suggested by tonesto7.  Do not use Safari Browser, use Chrome.
