### ISSUE TITLE
(BUG) Single selected Thermostat name and checkbox not showing in Device Selection

### ISSUE THREAD

**Issue by techtomydoor** [tonesto7/homebridge-hubitat-tonesto7#44]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [x ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:32
-  Mobile App Version(Not required):
-  SmartApp Version:2.1.6
-  Device Handler Version:
-  Homebridge Version:
-  NodeJS Version:

## Expected Behavior
**Tell us what you think should be happening**
I selected a Thermostat device in the modal drop down and saved all the way through and the thermostat shows in the Home app. I now want to unselect that thermostat in Device Selection and the modal drop down should show the single Thermostat with the check box checked.

## Current Behavior
**What happens instead of the expected behavior?**
The modal drop down appears but is not very tall and there is no device or check box.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
I inspected the element in order to mess with the CSS to try to get the check box to show. To get the thermostat out of the selected devices, I removed 'type="hidden"' from the line <input type="hidden" name="deviceList" value="tstatList"> immediately above the HTML for the modal drop down. This showed a numerical input field which allowed me to delete the value and save, thus removing the device. 

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This sounds like a Hubitat issue.  I have no control over how the drop down is rendered.
