### ISSUE TITLE
Issue with Yale Lock

### ISSUE THREAD

**Issue by rferson** [tonesto7/homebridge-hubitat-tonesto7#45]
I have a Yale Smartlock that is connected via Hubitat (version 2.2.4.156).  The lock will lock and unlock properly using Hubitat and HomeKit and will update its status (locked vs. unlocked) but will not show any status other than unlocked in HomeKit.  I can control the lock via HomeKit without issue, it is just the reporting.

**Comment by tonesto7** [comment]
What more are you looking to see happen with the lock under HomeKit?

**Comment by rferson** [comment]
> What more are you looking to see happen with the lock under HomeKit?

Hubitat reports lock/unlock status properly. HomeKit stays on unlocked no matter what. I would like to see status report properly.

**Comment by tonesto7** [comment]
I'm not sure this is related to the plugin itself... I've experienced this with the recent versions of iOS.
Watch the logs for Homebridge and Hubitat to see if the lock events are being sent and received.

**Comment by rferson** [comment]
Logs are showing entires immediately after lock and unlock in hubitat. No
log entries in Homebridge......
