### ISSUE TITLE
(BUG) Smartthings button not showing up in list under "Buttons" 

### ISSUE THREAD

**Issue by gregveres** [tonesto7/homebridge-hubitat-tonesto7#49]
I have a Smartthings button with driver of Samsung Zigbee Button configured as a device in HE. 
After I installed the Homebridge app and go to the Device Selection UI, I click on the Buttons section but there are no devices shown under that list. 

Are buttons supported? 

---
## About Your Setup
-  How many devices are detected?: I am not sure what this means?
-  SmartApp Version:  plugin=2.1.3, mainApp=2.1.6}
-  Device Handler Version: I don't know how to find the version of the Samsung Zigbee button driver version
-  Homebridge Version: v1.1.7
-  NodeJS Version: v15.2.1

## Expected Behavior
I would have expected the Samsung smartthings button to show up under the buttons list. 

## Current Behavior
the list of buttons is empty

## Steps to Reproduce (for bugs)

1. have a zigbee button installed on HE and verify that it is recognized and that button presses register with HE
2. install the homebridge app
3. got to the configuration and select the buttons to select
4.the list is empty

## Context
**How has this issue affected you? What are you trying to accomplish?
I am trying to trigger my TV scene  by pressing the samsung button.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I'm working on getting buttons going with the plugin... Buttons worked on ST but the way Hubitat handles buttons adds significant complexity to the plugin logic.

This is the only item remaining before I release the next version

**Comment by gregveres** [comment]
Nice. Thanks for following up
