### ISSUE TITLE
HomeKit continuous arming for night

### ISSUE THREAD

**Issue by black01gt** [tonesto7/homebridge-hubitat-tonesto7#5]
Upgraded to 1.5.5 and still getting continuous arming when arming at night.

**Comment by walksonair** [comment]
Same /w me. Also see that there is a mismatch between states of devices and what HomeKit shows. For example, light is actually off (and has been for a while) but HomeKit shows it's on. Toggling light in Home App resyncs status. Maybe related to continuous mode change?

**Comment by seannymurrs** [comment]
I'm also seeing the continuous arming issue with the night HSM mode.

**Comment by black01gt** [comment]
> Same /w me. Also see that there is a mismatch between states of devices and what HomeKit shows. For example, light is actually off (and has been for a while) but HomeKit shows it's on. Toggling light in Home App resyncs status. Maybe related to continuous mode change?

I am having the same issue with one of my dimmer switches. Odd thing is I removed it from the homebridge app in Hubitat and it still shows up and works. Odd thing also it works and reports correctly at home. But if I’m off my network that is when it will say it’s on when it’s not. Turn it off and a few mins later it shows on again.

**Comment by seannymurrs** [comment]
Still seeing the continuous arming of the Night HSM mode. Any updates on if a fix is likely?

**Comment by black01gt** [comment]
Seems to be working fine now. Thanks
