### ISSUE TITLE
(BUG) Argument Type Mismatch on v2.2.0

### ISSUE THREAD

**Issue by devenbj** [tonesto7/homebridge-hubitat-tonesto7#52]
Just updated Homebridge to latest version (no issues), and then Hubitat to the latest... After updating Hubitat, attempted to validate configuration when I received an error:
2020-12-28 11:49:06.520 pm errorjava.lang.IllegalArgumentException: argument type mismatch on line 340 (mainPage)
This occurred after clicking past the release notes. Did not have the ability to see the main app page... immediately displayed error.

Deleted my instance of Homebridge to recreate. Was able to get to the configuration page. After adding my lights and clicking Update, the same error occurred again.

Deleted my instance, and removed Homebdidge v2 Hubitat app (I use HPM to install). Installed it again, and went to create my instance again (same error).

Downgraded to 2.1.7 (manually from github - thought it was the previous version, fairly certain I grabbed Dec 7th code). Same error / different line number:
2020-12-29 12:15:46.208 am errorjava.lang.IllegalArgumentException: argument type mismatch on line 328 (deviceSelectPage)

Downgraded to 2.1.6 (manually from github). No errors. Homebridge is working as it did before (old Hubitat groovy app, new homebridge plugin, no issues).

Let me know if there is any additional troubleshooting I can do to assist... Thanks!

**Comment by devenbj** [comment]
Did some more troubleshooting. It worked great until the last commit on Nov 25th (error slightly different, and app wouldn't load at all). This is the broken commit: https://github.com/tonesto7/homebridge-hubitat-tonesto7/commit/1e8f110580bc8b1e622dffc06c239aedcfc2664b#diff-d56f6359d240f69e4164425b599d08869574fc013b9e5727951048914db12c5b

**Comment by j6s33m** [comment]
Log from Hubitat. Having same issue...but mine says line 351 (not 340 like original poster). This is new with v2.2.0

Fortunately, homebridge still functions, but i cannot make any device changes or additions in Hubitat. The app takes me to an error page ... which redirects to logs (error above in logs).

app:22732020-12-29 11:41:53.448 am errorjava.lang.IllegalArgumentException: argument type mismatch on line 351 (startPage)

**Comment by tonesto7** [comment]
I'm investigating right now

**Comment by j6s33m** [comment]
That fixed it. Thank you!

**Comment by devenbj** [comment]
Fixed for me, too! Thanks for the prompt update!
