### ISSUE TITLE
(BUG) Motion Sensors not reporting into Homebridge from Hubitat

### ISSUE THREAD

**Issue by DaveGraham123456** [tonesto7/homebridge-hubitat-tonesto7#54]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [ ??] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:
12
-  SmartApp Version:
Not sure what this means so I will spray information 
homebridge-hubitat-tonesto7 v2.2.1
@Field static final String appVersionFLD  = "2.1.6"

-  Device Handler Version:
Not sure where to find this.

-  Homebridge Version:
v1.1.7
-  NodeJS Version:
v12.18.3
--

## Expected Behavior
I have Konnected Apps installed on Hubitat.  They successfully register. I have two boards, one with Reed switches (Konnected Connect app) , the other board has motion (Konnected Pro app).  These require different apps.
I am able to see them in Hubitat.  They all trigger when they are supposed to.
I can see all the devices be put in the default room in homekit.
I would expect the reed switches to show when the doors open and the motion sensors to indicated motion.

## Current Behavior
The reed switches work in Homekit, but the motion sensors do not.  In Hubitat I see the motion sensor show movement.  In the device page the current states switches from motion: inactive to motion: active when I make my children jump in front of them.  This happens to all of them.

## Context
**How has this issue affected you? What are you trying to accomplish?  Just trying to see motion detected in homekit.

Two things I noticed, 1. Homebridge v2 app in hubitat says Code Update Available app v2.2.1.  I have no idea how to update it.

2. This is the problem I think: When I go to Apps->Homebridge and click the settings cog (in Hubitat) I see in sensorlist all the sensors.  But in Event subscriptions, I see only the set of sensors working.

Love the app.  When looking for an answer, your "Hey how about a donation" popped up, which I did.  sorry it wasn't more.

![image](https://user-images.githubusercontent.com/68233868/103466925-c974a080-4d9d-11eb-8a87-d5283c5f4b83.png)

![image](https://user-images.githubusercontent.com/68233868/103466938-ddb89d80-4d9d-11eb-82c0-de102d5e3e31.png)

**Comment by DaveGraham123456** [comment]
evidence that my motion sensors are in fact functioning

![image](https://user-images.githubusercontent.com/68233868/103466986-56b7f500-4d9e-11eb-832a-39c93e2d8408.png)

**Comment by tonesto7** [comment]
first thing I see is you are not running the most recent homebridge app version on hubitat.

Under Event Subscriptions are you seeing motionSensor events being subscribed to?

**Comment by DaveGraham123456** [comment]
Hi dude 

Yes I mentioned in the bug that I am not running the latest and it is not clear how to update

The 2nd thing I reported is I can see them not subscribed.  I think I even included a screen grab

How do I update?
How do I add them to the subscription?

Dave

Sent from my iPhone

On 11 Jan 2021, at 4:04 am, tonesto7 <notifications@github.com> wrote:

﻿
first thing I see is you are not running the most recent homebridge app version on hubitat.

Under Event Subscriptions are you seeing motionSensor events being subscribed to?
