### ISSUE TITLE
(BUG) Null device cannot be removed.

### ISSUE THREAD

**Issue by andydvsn** [tonesto7/homebridge-hubitat-tonesto7#57]
Looks like I managed to delete a switch from my system without removing it from Homebridge v2 first, which has resulted in this:

![image](https://user-images.githubusercontent.com/1003682/104906649-e3a4a600-597b-11eb-960e-71446b901caf.png)

Rebooting doesn't help, adding or removing other devices also no help. And, of course, there's no null device for me to go and tinker with.

It's largely a cosmetic issue as it's not affecting the operation of the app in any way that I can ascertain.

**Comment by tonesto7** [comment]
Thanks for reporting.  

It's a silly bug in the duplicate device detection. I will try to address it when I get some time.

**Comment by andydvsn** [comment]
Fantastic, thank you for your work on this. It's the cornerstone of how I do my home automation now. :)
