### ISSUE TITLE
(BUG) Shades behaving the opposite

### ISSUE THREAD

**Issue by roficas** [tonesto7/homebridge-hubitat-tonesto7#58]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [x ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 3
-  Mobile App Version(Not required):
-  SmartApp Version: Version: v2.2.2, Plugin: v2.2.2
-  Device Handler Version: homebridge-hubitat-tonesto7 v2.2.2
-  Homebridge Version: v1.2.5
-  NodeJS Version: v12.20.1

## Expected Behavior
When I tell the shades to close, they should go to 100% and close. When opening, go to 0%. Also, anything in between. 

## Current Behavior
When I tell the shades to close, it opens. When I say 60% open, it's 60% closed. 

## Steps to Reproduce (for bugs)

1. open HomeKit and try to open the shade
2. that's it.

## Context
I have Ikea Fyrtur shades and they work properly when I set the level in Hubitat device screen. When I try through home bridge or HomeKit, they behave the opposite: it shows like 10% open but it's in fact 10% closed. Also, it doesn't understand closed and open as a status (for 0 or 100%). It looks like the level could be sent as 100-level (I may try to change the code on my end to test, but not sure if I got everything right yet).

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by thitemple** [comment]
I came here to open the same issue.

**Comment by roficas** [comment]
I updated plugin and app and it’s still the same. Any insights?

**Comment by tonesto7** [comment]
This is not an issue with the plugin... The issue is with the drivers you are using I'm not sure they are set up to work like standard shades because I and many others are using shades and it works fine. 

Are you using custom drivers or are they built-in drivers?

**Comment by roficas** [comment]
I am using custom drivers (I'll check them), BUT when I'm operating from within Hubitat, everything works fine - that's why I'm betting on something in between Hubitat and HomeKit... Would you like to test somehow and have some debug logs?

**Comment by tonesto7** [comment]
If you can enable debug logs on the hubitat app and collect the logs from Homebridge and Hubitat? I need to see the output while you are executing commands

**Comment by roficas** [comment]
Sorry for the delay - I didn't get the notification from GitHub.

I just tried to **open** the shades using HomeKit and this is the log I pulled from Hubitat:

```
dev:7542021-04-29 10:18:25.495 am debugdescription:- catchall: 0104 0102 01 01 0040 00 83BB 00 00 0000 0B 01 0500
app:382021-04-29 10:18:25.083 am info Homebridge (v2.5.3) |  | Office Shade | Command [setLevel()] | Process Time: (82ms)
app:382021-04-29 10:18:25.074 am info Homebridge (v2.5.3) | Command Successful for Device Office Shade | Command [setLevel(100)]
dev:7542021-04-29 10:18:25.066 am infosetLevel()
app:382021-04-29 10:18:25.048 am info Homebridge (v2.5.3) | Plugin called Process Command | DeviceId: 754 | Command: (setLevel) | Param1: (100)
```

As you can see, it received a **close** command. Looking at HomeBridge, this is how the plugin translated:

```
[29/04/2021, 15:18:22] [Hubitat-v2] Sending Device Command: setLevel | Value: {"value1":100} | Name: (Office Shade) | DeviceID: (754) | UsingCloud: (false)
[29/04/2021, 15:18:23] [Hubitat-v2] [Device Event]: (Office Shade) [LASTCHECKIN] is 2021 Apr 29 Thu 10:18:25 AM
```

At the same time, HomeKit is showing me the shade is **open**.

![image](https://user-images.githubusercontent.com/8245962/116566546-da10cf80-a8d4-11eb-8dba-89232de078e8.png)

Please let me know what other information I could share.

**Comment by roficas** [comment]
I also tried to set as 95% open in HomeKit and it actually sent the command as closed:
```
[29/04/2021, 15:24:22] [Hubitat-v2] Sending Device Command: setLevel | Value: {"value1":95} | Name: (Office Shade) | DeviceID: (754) | UsingCloud: (false)
[29/04/2021, 15:24:22] [Hubitat-v2] [Device Event]: (Office Shade) [LASTCHECKIN] is 2021 Apr 29 Thu 10:24:24 AM
```
After that, it doesn't update the status correctly on homebridge, but Hubitat has it current.

**Comment by mbudnek** [comment]
@roficas If you're still having trouble with this, there's an updated driver for the Fyrtur blinds [here](https://gist.github.com/MorningZ/87f29c57bd4b6d45df8df33b65187eb0) that reverses them so that 0% is fully-closed and 100% is fully-open.

There are other shade drivers that have this same behavior though.  I ended up adding a "reverse direction" toggle for blinds in the custom Google Home integration I maintain to accommodate them; seems like something similar could be done here.
