### ISSUE TITLE
Unable to access lights after 2.3.3 update.

### ISSUE THREAD

**Issue by hpstephens** [tonesto7/homebridge-hubitat-tonesto7#67]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ Yes] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [Yes ] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 10
-  Hubitat App Version: 2.2.5.131
-  Homebridge Plugin Version: 2.3.3
-  Homebridge Version: 1.3.1
-  NodeJS Version: 14.16.0

## Expected Behavior
**Tell us what you think should be happening**
Should be able to control all lights from HOME app. or Homebridge accessories.

## Current Behavior
**What happens instead of the expected behavior?**

Unable to control any of my lights. I can see their status (EX> off or on) but unable to turn them off or on. I can control them from the hubitat app.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. After rebooting both hubitat and homebridge, a question came up asking if I wanted to link the adaptive lights. I defaulted to no and now no lights work.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

Need to be able to control the lights in the house.
[homebridge.log (2).txt](https://github.com/tonesto7/homebridge-hubitat-tonesto7/files/6059564/homebridge.log.2.txt)

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
I apologize but i haven't been able to duplicate this.   Can you try adding the lights to the new input in the device selection page that blocks Adaptive Lighting?

**Comment by spikenheimer** [comment]
symptomatically this feels similar to closed issue #65 
@hpstephens do you have any logging turned on or any errors there?

**Comment by hpstephens** [comment]
i found that when package manager installed the update, the message to check for the new feature for the bulbs. at that time the database became corrupt. i had package manager reinstall the package and said no to the question. everything is now running again.
