### ISSUE TITLE
"This plugin generated a warning from the characteristic 'Target Fan State': characteristic was expected valid number and received NaN.

### ISSUE THREAD

**Issue by Euripides81** [tonesto7/homebridge-hubitat-tonesto7#69]
Plugin Version: 2.4.1

[homebridge-hubitat-tonesto7] This plugin generated a warning from the characteristic 'Target Fan State': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.

Per the website suggestion, I'm reaching out:

"If you see this message in the log, the plugin threw an unhandled exception while processing the SET or GET request for the characteristic.

👤 If you're an end user, you should report this issue to the plugin developer.

Run Homebridge in debug mode (-D) to provide the developer with the full stack trace.

🧑‍💻 If you're the plugin developer:

Make sure you catch and handle any potential exception that may be thrown while processing your plugin's GET or SET handlers.
You can get a full stack trace to see where this exception was thrown by starting Homebridge in debug mode (-D)."

**Comment by jtp10181** [comment]
I just got this setup and installed so everything is up to date, I am getting this error with a Thermostat w/ Fan

**Comment by intrepidsilence** [comment]
I am getting this as well, with a Brightness value: 
This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number)

This was a problem with the SmartThings plugin as well. It would be really great if these errors could be dealt with once and for all. I know you have said they can be ignored but having them filling up the logs is not ideal and it would be better to have them gone. Is there a default value needed in some cases for some device types to keep them within valid values?
