### ISSUE TITLE
Device state doesn't get updated in Homebridge

### ISSUE THREAD

**Issue by krharrison1** [tonesto7/homebridge-hubitat-tonesto7#70]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [x ] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?:25
-  Hubitat App Version: v2.4.1
-  Homebridge Plugin Version: v2.4.1
-  Homebridge Version:  1.2.5, 1.3.2
-  NodeJS Version: 13.11.0

## Expected Behavior
Turn on switch (setup in Homebridge v2 app) in Hubitat dashboard, the accessory switch in Homebridge should turn on. 
Turn off switch in Hubitat dashboard, the accessory switch in Homebridge should turn off. 

## Current Behavior
**What happens instead of the expected behavior?**
Turning on the switch from Hubitat works ok. I can see in the homebridge logs that the switch is on:
[3/7/2021, 11:18:46 am] [Hubitat-v2] INFO: [Device Event]: (Master Desk Lamp) [SWITCH] is on

Turning off the switch from Hubitat isn't working. I can see in the homebridge logs that the switch was turned off:
[3/7/2021, 11:18:50 am] [Hubitat-v2] INFO: [Device Event]: (Master Desk Lamp) [SWITCH] is off

But the status change isn't reflected in the homebridge accessory - it still shows on. However, if I refresh the Accessories page in homebridge, the status of the accessory will correctly update to off. 

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Turn switch on from hubitat, observe status of corresponding accessory in homebridge (device state changes correctly)
2. Turn switch off from hubitat, observe status of accessory. (device state doesn't change)
3. Check homebridge logs to see if on/off events were received (both on and off events appear in logs)
4. Refresh homebridge accessory page from broswer and observe that device status updates correctly 

## Context
**How has this issue affected you? What are you trying to accomplish?
I am using the Homebridge v2 plugin to control several iHome outlets from Hubitat. This setup was working correctly until the recent updates to homebridge and homebridge-hubitat. I have downgraded homebridge back to 1.2.5 yet this behavior still exists. I'm still not sure if this is an issue with homebridge or the changes that were made to homebridge-hubitat to accommodate the latest homebridge update.  Any help would be GREATLY appreciated as this has caused a number of automations to fail. Thank you!

**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment]
This issue should be resolved with the latest plugin releases￼￼

**Comment by krharrison1** [comment]
Thanks for fixing this!
