### ISSUE TITLE
Unable to disable fan / cooling from thermostat

### ISSUE THREAD

**Issue by cjattard** [tonesto7/homebridge-hubitat-tonesto7#73]
Please can I request the option to disable type ‘Fan’ in the filter menu?

background - One of the nest thermostats in my house supports fan function - but we don’t have a fan. All Nest thermostats in hubitat are currently exposed to homebridge as thermostats with fans.

thanks

**Comment by cjattard** [comment]
I just played around with this some more and have a bit more data! It appears the thermostat or thermostat (heat only) mode is not stripping out the cooling function - which doesn’t exist on the driver type. this is using the Google SDM integration. 

![558C1233-DC58-41FA-AB2B-8EEE894168CD](https://user-images.githubusercontent.com/45669214/110541284-744b6700-811f-11eb-9659-d04ecbd382df.jpeg)
![56AF13E2-568D-460F-A1EE-369F44E31F83](https://user-images.githubusercontent.com/45669214/110541298-76152a80-811f-11eb-8e09-51b5174e716f.jpeg)
![05D15AE6-B730-402F-8F81-D5B9257138AA](https://user-images.githubusercontent.com/45669214/110541303-76adc100-811f-11eb-830e-fef9becb8e0d.jpeg)
![08B22D6F-A218-4CA6-9D5B-C30F087F9355](https://user-images.githubusercontent.com/45669214/110541307-77deee00-811f-11eb-8108-bc314eb94017.jpeg)
![5087A730-B56E-46C7-BC50-E1D42E7C7370](https://user-images.githubusercontent.com/45669214/110541311-78778480-811f-11eb-8692-86ffd1e1d080.jpeg)

**Comment by tonesto7** [comment]
I will add a new input which allows filtering of thermostat fans.

**Comment by nbrewk** [comment]
Bumping this up. I have a heat-only setup  (also using Google SDM to integrate a Nest thermostat) and it's definitely not stripping out the Cooling Threshold. It keeps getting logged in the Homebridge log. Please look into this, @tonesto7!
