### ISSUE TITLE
Request to filter out leak Sensor

### ISSUE THREAD

**Issue by saiajin** [tonesto7/homebridge-hubitat-tonesto7#78]
**Is your feature request related to a problem? Please describe.**

I have an Aqara Motion Sensor that exposes as all sensors...I can filter out all capabilities except leak sensor and it exposes to ￼homekit as both a motion and a leak sensor with a leak detected... I have 4 other sensors I want to add so this could be problematic...
**Describe the solution you'd like**
Can u add the ability to filter out the leak sensor or suggest a possible solution?

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/71667075/114259783-460eb080-9985-11eb-97ab-191a7267acc3.jpeg)

**Comment by tonesto7** [comment]
I apologize for missing this as an available filter.  I will add it in real quick today

**Comment by tonesto7** [comment]
I've added this into today's release.  

Just update the app and you should be able to use it...

**Comment by saiajin** [comment]
Awesome thank you!  No need to apologize i'm glad it wasnt me and I understand with all you take care of stuff can slip through the cracks... BTW I don't know why the icon isn't updating:

<img width="887" alt="Screen Shot 2021-04-10 at 8 36 00 AM" src="https://user-images.githubusercontent.com/71667075/114275631-0e7d2400-99d8-11eb-9792-ac1f0834c17f.png">
