### ISSUE TITLE
[Feature Request] Outlet / Power Point support

### ISSUE THREAD

**Issue by phyber** [tonesto7/homebridge-hubitat-tonesto7#79]
**Is your feature request related to a problem? Please describe.**

Currently, Homebridge-Hubitat lacks support for outlets / power points and users must add these as switches.

On the surface, this appears to be the same functionality, but it's not quite the same.  HomeKit responds to these differently. Under `Home.app` an outlet / power point may be displayed as:

  - Fan
  - Light
  - Power Point

While a Switch may be displayed as:

  - Fan
  - Light
  - Switch

This affects the following `Home.app` functionality:

  - Icons that can be used for the outlet / power point are incorrect (switch and power point icons differ)
  - Grouping of outlet / power point statuses in `Home.app` is now incorrect, any outlets / power points used via Homebridge-Hubitat are grouped as switches instead of outlets / power points.  This is important if using Homebridge-Hubitat along with native HomeKit outlets / power points.

**Describe the solution you'd like**

Support for Outlets / Power Points so that the `Home.app` sees these devices correctly.

**Describe alternatives you've considered**

Currently just employing the workaround of adding outlets / power points as switches.

**Additional context**

Thanks for the work on these plugins, it's great to be able to add Hubitat devices to HomeKit 👍

**Comment by tonesto7** [comment]
I don't want you to think i'm ignoring this request.  I will begin working on this soon.  I've been tied up at work and my projects have been put on the back burner.

**Comment by tonesto7** [comment]
I just pushed out code with support for outlets

**Comment by phyber** [comment]
> I don't want you to think i'm ignoring this request.

No worries, the feature was in no way urgent.

> I just pushed out code with support for outlets

Thanks for implementing it so quickly :)
