### ISSUE TITLE
Aeotec Water Sensor 7 - Events Not Passing to Homebridge

### ISSUE THREAD

**Issue by cscott365** [tonesto7/homebridge-hubitat-tonesto7#80]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: Currently 1 (Only Water Sensor I have added) and 8 other devices with no issues.
-  Hubitat App Version: 2.2.6.140
-  Homebridge Plugin Version: 2.5.3
-  Homebridge Version: 1.3.4
-  NodeJS Version: 

## Expected Behavior
 Water sensor wet/dry data should be passing to Homebridge and connected Homekit

## Current Behavior
 It appears that the wet/dry status for the water sensor is not being sent to Homebridge. The open/close status is working for my door/window sensors just fine. The temperature and humidity data is coming through just fine as well. Just not the wet/dry status.

## Steps to Reproduce (for bugs)

1. Connect Sensor to ZWave Topology
2. Add sensor to Homebridge and MakerAPI apps
3. Verify that sensor is in Homekit and visible
4. Make sensor contacts connect for wet status and disconnect for dry status
5. Verify that Hubitat is recording the status change
6. There is NO change in Homebridge or Homekit

## Context
Looking for the sensor to alert when the wet/dry switch is tripped to apply automation like shutting off the water.

**Comment by cscott365** [comment]
Device is also chosen as a "Switch" in the Homebridge V2 App in Hubitat.

Here are the events in Hubitat that do not seem to be getting to Homebridge:

water | dry |   | Laundry Water is dry | DEVICE |   | 2021-04-13 02:47:54.773 PM PDT
water | wet |   | Laundry Water is wet | DEVICE |   | 2021-04-13 02:47:41.862 PM PDT
water | dry |   | Laundry Water is dry | DEVICE |   | 2021-04-13 02:27:23.528 PM PDT
water | wet |   | Laundry Water is wet | DEVICE |   | 2021-04-13 02:26:50.825 PM PDT
water | dry |   | Laundry Water is dry | DEVICE |   | 2021-04-13 02:22:06.398 PM PDT
water | wet |   | Laundry Water is wet | DEVICE |   | 2021-04-13 02:22:00.545 PM PDT
water | dry |   | Laundry Water is dry | DEVICE |   | 2021-04-13 02:21:37.528 PM PDT
water | wet |   | Laundry Water is wet | DEVICE |   | 2021-04-13 02:21:36.749 PM PDT

**Comment by cscott365** [comment]
Curious if the following code from: HE_DeviceCharacteristics.js is part of the issue:

```
    water_sensor(_accessory, _service) {
        _accessory.manageGetCharacteristic(_service, _accessory, Characteristic.LeakDetected, "water");
        _accessory.manageGetCharacteristic(_service, _accessory, Characteristic.StatusActive, "status");
        if (_accessory.hasCapability("Tamper Alert")) _accessory.manageGetCharacteristic(_service, _accessory, Characteristic.StatusTampered, "tamper");
        _accessory.context.deviceGroups.push("window_shade");
        return _accessory;
    }
```

I see the deviceGroups.push is sending back "window_shade" and perhaps it should be "water_sensor".

**Comment by cscott365** [comment]
Pulled down the MakerAPI plugin and the leak sensor properly reports in Homebridge and then Homekit with that setup, so highly confident it is somewhere in this plugin code.

**Comment by cscott365** [comment]
Was hoping to get some form of feedback on this by now. It appears that it is not a priority, so I have removed the plugin and went a different route via node-red to get my Hubitat devices back into Homekit. Hopefully at some point you can fix this and get it into the plugin.

**Comment by tonesto7** [comment]
Sorry this has sat with no response. I think your observation in the code is correct. I will get it fixed and pushed out this evening

**Comment by tonesto7** [comment]
I pushed out a fix but I'm not 100% it's your issue.  I have about 10 water sensors of various brands and they all work for me so hopefully, this solves your issue.
