### ISSUE TITLE
(BUG) Garage not detected

### ISSUE THREAD

**Issue by nickpalmer** [tonesto7/homebridge-hubitat-tonesto7#83]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?:20
-  Hubitat App Version: 2.5.6
-  Homebridge Plugin Version: 2.5.6
-  Homebridge Version: 1.3.4
-  NodeJS Version: 14.15.4

## Expected Behavior

Garage Door created by Vivint plugin should show up

## Current Behavior

Garage Door created by Vivint plugin doesn't show up in Hubitat, but it shows in Homebridge and in the Home app.

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Install Vivint plugin and configure
2. Install Homebridge plugin and configure
3. Note garage door doesn't show up

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

Cannot setup rules for the garage door in rules manager because it doesn't show up on the hubitat side.

Also tried with the MyQ plugin to Homebridge but that also doesn't show up in Hubitat.

---
Please include a copy of any relevant log output to assist in tracking down the bug

Happy to provide logs just not sure how to get them.

**Comment by tonesto7** [comment]
If the device has the garage door capability and the open and close commands then the plugin will identify it as a garage door.
