### ISSUE TITLE
(BUG) Hubitat app thinks that Homebridge plugin is out of date

### ISSUE THREAD

**Issue by zacs** [tonesto7/homebridge-hubitat-tonesto7#86]
## Verify the following before opening an trouble issue

-  [x] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: ~100
-  Hubitat App Version: 2.5.7
-  Homebridge Plugin Version: 2.5.7
-  Homebridge Version: 1.3.4
-  NodeJS Version: 14.16.0

## Expected Behavior
The app should not report that the Homebridge plugin is out of date. 

## Current Behavior
The app reports an older version of the Homebridge plugin, even when clicking through Done/Next. 

## Steps to Reproduce (for bugs)

1. Open the app on Hubitat

![image](https://user-images.githubusercontent.com/27705/121122224-e6425380-c7d5-11eb-9b78-ecf0f080105f.png)

2. Note the red text warning of an older version
3. Check to make sure I'm not crazy in Homebridge

![image](https://user-images.githubusercontent.com/27705/121122279-feb26e00-c7d5-11eb-8d4c-d569b8b8d782.png)

## Context
I don't think this actually impacts functionality at all -- everything seems to work fine, aside from the warning text.

**Comment by tonesto7** [comment]
This issue should have resolved itself automatically once the plugin restarted once and sent the version data to the app.
