### ISSUE TITLE
(BUG) {ENTER TITLE HERE} 

### ISSUE THREAD

**Issue by SANdood** [tonesto7/homebridge-hubitat-tonesto7#88]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x ] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [ x ] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 24
-  Hubitat App Version: 2.5.8
-  Homebridge Plugin Version: 2.5.8
-  Homebridge Version: 1.3.4
-  NodeJS Version: 14.17.0

## Expected Behavior
**Tell us what you think should be happening**
Unlocking a lock from the Hubitat side should be reflected in Home almost immediately.

## Current Behavior
**What happens instead of the expected behavior?**
Lock status doesn't get updated in the Home side for several minutes, up to a couple of hours. I can see that the command is sent by the Homebridge plugin, but it isn't registered by Home.

The Hubitat logs show the commands being sent to lock/unlock. But the Homebridge log doesn't show the lock being locked or unlocked...

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1. Lock or Unlock a lock
2. Note that command is logged on the Hubitat side
3. Note that the command is NOT logged on the Homebridge side
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**
I just want the lock status updated immediately, so that my Home automations are executed in a timely manner

---
Please include a copy of any relevant log output to assist in tracking down the bug

Homebdige on Hubitat:
app:192021-06-23 08:31:26.418 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:31:26.367 am info Homebridge (v2.5.8) | Sending DEVICE Event (Front Door Lock | LOCK: unlocked)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:19:10.745 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:19:10.707 am info Homebridge (v2.5.8) | Sending DEVICE Event (Front Door Lock | BATTERY: 100%)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:18:11.845 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:18:11.802 am info Homebridge (v2.5.8) | Sending DEVICE Event (Basement Dehumidifier | SWITCH: off)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:15:50.634 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:15:50.575 am info Homebridge (v2.5.8) | Sending DEVICE Event (Cellar Dehumidifier | SWITCH: off)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:10:14.124 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:10:14.070 am info Homebridge (v2.5.8) | Sending DEVICE Event (Front Door Lock | LOCK: locked)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:10:11.657 am info Homebridge (v2.5.8) |  | Front Door Lock | Command [lock()] | Process Time: (21ms)
app:192021-06-23 08:10:11.652 am info Homebridge (v2.5.8) | Command Successful for Device Front Door Lock | Command [lock()]
app:192021-06-23 08:10:11.634 am info Homebridge (v2.5.8) | Plugin called Process Command | DeviceId: 25 | Command: (lock)
app:192021-06-23 08:08:39.950 am info Homebridge (v2.5.8) |  | Front Door Lock | Command [unlock()] | Process Time: (65ms)
app:192021-06-23 08:08:39.945 am info Homebridge (v2.5.8) | Command Successful for Device Front Door Lock | Command [unlock()]
app:192021-06-23 08:08:39.883 am info Homebridge (v2.5.8) | Plugin called Process Command | DeviceId: 25 | Command: (unlock)
app:192021-06-23 08:06:19.069 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:06:18.982 am info Homebridge (v2.5.8) | Sending DEVICE Event (Front Door Lock | LOCK: unlocked)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:05:51.781 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:05:51.741 am info Homebridge (v2.5.8) | Sending DEVICE Event (Basement Dehumidifier | SWITCH: on)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:05:43.707 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:05:43.665 am info Homebridge (v2.5.8) | Sending DEVICE Event (Front Door Lock | LOCK: locked)  to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:05:40.958 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:05:40.914 am traceHomebridge (v2.5.8) | sendDeviceRefreshCmd: 192.168.0.41:8002
app:192021-06-23 08:05:37.983 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)
app:192021-06-23 08:05:37.910 am traceHomebridge (v2.5.8) | updateServicePrefs: 192.168.0.41:8002
app:192021-06-23 08:05:32.856 am debugHomebridge (v2.5.8) | -----------------------------------------------
app:192021-06-23 08:05:32.853 am info Homebridge (v2.5.8) | Subscribed to (20 Physical Devices)
app:192021-06-23 08:05:32.850 am debugHomebridge (v2.5.8) | Subscribed to (0) Thermostat (HeatOnly) Devices
app:192021-06-23 08:05:32.847 am debugHomebridge (v2.5.8) | Subscribed to (0) Thermostat + Fan Devices
app:192021-06-23 08:05:32.844 am debugHomebridge (v2.5.8) | Subscribed to (0) Thermostat Devices
app:192021-06-23 08:05:32.842 am debugHomebridge (v2.5.8) | Subscribed to (0) Garage Door Devices
app:192021-06-23 08:05:32.838 am debugHomebridge (v2.5.8) | Subscribed to (0) Window Shade Devices
app:192021-06-23 08:05:32.334 am debugHomebridge (v2.5.8) | Subscribed to (9) Switch Devices
app:192021-06-23 08:05:32.030 am debugHomebridge (v2.5.8) | Subscribed to (5) Outlet Devices
app:192021-06-23 08:05:31.957 am debugHomebridge (v2.5.8) | Subscribed to (1) Other Devices
app:192021-06-23 08:05:31.954 am debugHomebridge (v2.5.8) | Subscribed to (0) Speaker Devices
app:192021-06-23 08:05:31.951 am debugHomebridge (v2.5.8) | Subscribed to (0) Sensor Devices
app:192021-06-23 08:05:31.949 am debugHomebridge (v2.5.8) | Subscribed to (0) Holdable Button Devices
app:192021-06-23 08:05:31.946 am debugHomebridge (v2.5.8) | Subscribed to (0) Double Tapable Button Devices
app:192021-06-23 08:05:31.943 am debugHomebridge (v2.5.8) | Subscribed to (0) Pushable Button Devices
app:192021-06-23 08:05:31.940 am debugHomebridge (v2.5.8) | Subscribed to (0) Fans (5SPD) Devices
app:192021-06-23 08:05:31.937 am debugHomebridge (v2.5.8) | Subscribed to (0) Fans (4SPD) Devices
app:192021-06-23 08:05:31.934 am debugHomebridge (v2.5.8) | Subscribed to (0) Fans (3SPD) Devices
app:192021-06-23 08:05:31.931 am debugHomebridge (v2.5.8) | Subscribed to (0) Fan Devices
app:192021-06-23 08:05:31.929 am debugHomebridge (v2.5.8) | Subscribed to (0) Light Devices (Block Adaptive Lighting)
app:192021-06-23 08:05:31.717 am debugHomebridge (v2.5.8) | Subscribed to (5) Light Devices
app:192021-06-23 08:05:25.681 am info Homebridge (v2.5.8) | Subscribed to (4 Location Modes)
app:192021-06-23 08:05:25.678 am info Homebridge (v2.5.8) | Starting Device Subscription Process...

-------
Homebridge log (note, does not show lock being locked/unlocked around 8:31AM

Preparing Advertiser for 'Homebridge 734C C907' using bonjour-hap backend!
Setup Payload:
X-HM://0023R6DH6F6G0
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 172-07-482 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 734C C907' using bonjour-hap backend!
[6/23/2021, 7:57:08 AM] Homebridge v1.3.4 (Homebridge 734C) is running on port 51820.
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Temperature Unit is Now: (F)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Updating Global Values | HubIP: 192.168.0.41 | UsingCloud: false
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Devices to Remove: (0) 
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Devices to Update: (15)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Devices to Create: (9) Bathroom Fan,Bathroom Fan Heater,Bathroom Fan Light,Bathroom Sink Light,Cellar Dehumidifier,Cellar Drain Pump,Living Room Lamp,Sitting Room Lamp,Weather Station Power
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Bathroom Fan | 84)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Bathroom Fan Heater | 83)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Bathroom Fan Light | 85)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Bathroom Sink Light | 86)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Cellar Dehumidifier | 91)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Cellar Drain Pump | 117)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Living Room Lamp | 28)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Sitting Room Lamp | 32)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Added Device: (Weather Station Power | 24)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Total Initialization Time: (1 seconds)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Unknown Capabilities: []
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Hubitat DeviceCache Size: (24)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] WebServer Initiated...
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Sending StartDirect Request to Hubitat | UsingCloud: (false)
[6/23/2021, 7:57:08 AM] [Hubitat-v2] Direct Connect Active | Listening at 192.168.0.41:8002
[6/23/2021, 7:57:11 AM] [Hubitat-v2] INFO: Your plugin version is up-to-date
[6/23/2021, 7:57:11 AM] [Hubitat-v2] Sending Plugin Status to Hubitat | UpdateAvailable: false | newVersion: 2.5.8
[6/23/2021, 8:02:12 AM] [Homebridge UI] Changes to config.json saved.
[6/23/2021, 8:08:40 AM] [Hubitat-v2] Sending Device Command: unlock | Name: (Front Door Lock) | DeviceID: (25) | UsingCloud: (false)
[6/23/2021, 8:10:11 AM] [Hubitat-v2] Sending Device Command: lock | Name: (Front Door Lock) | DeviceID: (25) | UsingCloud: (false)

**Comment by tonesto7** [comment]
If your seeing issues, it's related to communication between homebridge and habitat.  Unfortunately, I'm extremely confident that the code is not at fault here.  Looking at your logs it's not receiving a response back which tells me something is not working on your side.  It works fine with locks for everyone else.  
`app:192021-06-23 08:15:50.575 am info Homebridge (v2.5.8) | Sending DEVICE Event (Cellar Dehumidifier | SWITCH: off) to Homebridge at (192.168.0.41:8002)
app:192021-06-23 08:10:14.124 am errororg.codehaus.groovy.runtime.InvokerInvocationException: java.lang.Exception: No response data exists for async request (asyncHttpCmdResp)`  The error your seeing in the Hubitat logs says that HE can't reach the plugin to send the event. Make sure the plugin is configured to use the non standard port 8002 
 If you are able to track down any bugs I will fix them immediately.

**Comment by SANdood** [comment]
Ignore this - something is more significantly wrong, since NONE of my devices are being updated on the Home side - I must have something configured incorrectly...

**Comment by SANdood** [comment]
***My Bad*** The problem was caused by the `Direct IP` - I had inadvertently set it to the address of the sending Hubitat hub, instead of the rPi Homebridge server.

**Comment by tonesto7** [comment]
No problem at all @SANdood.   I remember you from ST :)
It happens to the best of us.  Especially me as I start getting older.
