### ISSUE TITLE
(BUG) Blinds always show as closing in Home app when open from 95% to 99%

### ISSUE THREAD

**Issue by mbudnek** [tonesto7/homebridge-hubitat-tonesto7#92]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [x] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 70
-  Hubitat App Version: 2.5.8
-  Homebridge Plugin Version: 2.5.8
-  Homebridge Version: 1.3.4
-  NodeJS Version: 14.17.1

## Expected Behavior
When the blinds are open, the tile in the Home app should show "Open"

## Current Behavior
When the blinds are open, the tile in the Home app shows "Closing..." with a spinning progress indicator

## Steps to Reproduce (for bugs)
1. Set the `round_levels` config to `true` in the Homebridge plugin config
2. Create a virtual shade device in Hubitat
3. Expose the virtual shade to Homebridge via the Hubitat app
4. Wait for the device to appear in the Home app
5. With the Home app open to a view that includes the virtual shade, set its position to 99 from Hubitat
6. Observe that the shade's tile changes to "Open"
7. Close the Home app
8. Re-open the Home app
9. Observe that the shade's tile has changed to "Closing..."

## Context
I have a z-wave shade driver that reports its `level` and `position` attributes as 99 when fully open, as is fairly normal of Hubitat drivers, so this issue appears whenever the shade is fully open.  My guess is that the `round_levels` config isn't getting applied consistently to the two attributes, and that's causing the problem.

This is a purely cosmetic issue; functionality seems correct (i.e. I can tap the tile to close the shade, Siri will say the shade is open if asked, etc).

**Comment by tonesto7** [comment]
So I've been doing some testing and it seems that the driver may not be sending back a status of closed.
I tested using a virtual - shade device.
![image](https://user-images.githubusercontent.com/1835933/126397300-584f5f61-cd8f-4d7a-b401-dd6eb523494e.png)
