### ISSUE TITLE
(BUG) Hubitat sensor never appears in HomeKit

### ISSUE THREAD

**Issue by spud** [tonesto7/homebridge-hubitat-tonesto7#93]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [X] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 56
-  Hubitat App Version: 2.5.8
-  Homebridge Plugin Version: 2.5.7
-  Homebridge Version: 1.3.4 
-  NodeJS Version: 14.17.1

## Expected Behavior
Third Floor Sensor (ZooZ 4-in-1) should appear in HomeKit after being added in Hubitat Homebridge app

## Current Behavior
Third Floor Sensor does not appear in HomeKit

## Steps to Reproduce (for bugs)
I have added the "Third Floor Sensor" via Hubitat in the same way as the other 18 sensors were added. I have removed it, re-added, renamed it and re-added it, etc. Never shows up.

The "View Device Debug Data" shows this:

```
{
    "name": "Third floor hallway sensor",
    "basename": "Zooz 4-in-1 Sensor",
    "deviceid": "1",
    "status": "ACTIVE",
    "manufacturer": "Unknown",
    "model": "Zooz 4-in-1 Sensor",
    "deviceNetworkId": "02",
    "lastActivity": "2021-06-27T18:17:35+0000",
    "capabilities": [
        "Battery",
        "Configuration",
        "IlluminanceMeasurement",
        "MotionSensor",
        "Refresh",
        "RelativeHumidityMeasurement",
        "Sensor",
        "TamperAlert",
        "TemperatureMeasurement"
    ],
    "capabilities_processed": {
        "Battery": 1,
        "Configuration": 1,
        "IlluminanceMeasurement": 1,
        "MotionSensor": 1,
        "Refresh": 1,
        "RelativeHumidityMeasurement": 1,
        "Sensor": 1,
        "TamperAlert": 1,
        "TemperatureMeasurement": 1
    },
    "capabilities_filtered": [
        
    ],
    "commands": [
        "configure",
        "refresh"
    ],
    "commands_processed": [
        
    ],
    "customflags": {
        
    },
    "attributes": {
        "battery": 20,
        "humidity": 59,
        "illuminance": 50,
        "motion": "active",
        "syncStatus": "Synced",
        "tamper": "clear",
        "temperature": 79.62
    },
    "attributes_processed": {
        "battery": 20,
        "humidity": 59,
        "illuminance": 50,
        "motion": "active",
        "syncStatus": "Synced",
        "tamper": "clear",
        "temperature": 79.62
    },
    "eventHistory": [
        "2021-06-27 14:17:35.104 | [motion] | (active)",
        "2021-06-27 14:17:14.996 | [illuminance] | (50 lux)",
        "2021-06-27 14:17:14.988 | [humidity] | (59 %)",
        "2021-06-27 14:17:14.953 | [temperature] | (79.62 \u00b0F)",
        "2021-06-27 14:11:44.367 | [illuminance] | (39 lux)",
        "2021-06-27 14:11:44.307 | [temperature] | (79.64 \u00b0F)",
        "2021-06-27 14:06:09.499 | [illuminance] | (50 lux)",
        "2021-06-27 14:06:09.451 | [humidity] | (58 %)",
        "2021-06-27 14:06:09.416 | [temperature] | (79.65 \u00b0F)",
        "2021-06-27 14:03:23.882 | [illuminance] | (40 lux)",
        "2021-06-27 14:03:23.832 | [temperature] | (79.58 \u00b0F)",
        "2021-06-27 13:52:18.895 | [illuminance] | (50 lux)",
        "2021-06-27 13:52:18.876 | [humidity] | (57 %)",
        "2021-06-27 13:46:43.959 | [illuminance] | (38 lux)",
        "2021-06-27 13:46:43.935 | [humidity] | (58 %)",
        "2021-06-27 13:46:43.906 | [temperature] | (79.38 \u00b0F)",
        "2021-06-27 13:38:23.918 | [illuminance] | (45 lux)",
        "2021-06-27 13:38:23.892 | [humidity] | (57 %)",
        "2021-06-27 13:38:23.854 | [temperature] | (79.46 \u00b0F)",
        "2021-06-27 13:35:38.203 | [illuminance] | (41 lux)"
    ]
}

```
But the "View Device Data Sent to Homebridge" does _not_ include this device.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by con40** [comment]
I have the same behavior for my Zigbee Locks - missing from "View Device Data Sent to Homebridge".

**Comment by tonesto7** [comment]
I'm not sure what to do with this as I haven't seen this issue and can't duplicate it.  What input did you add the sensor to in the hubitat app?

**Comment by con40** [comment]
@tonesto7 I have two zigbee (Yale) locks configured as "Other" Devices in the Homebridge V2 Hubitat App.  Curiously, one started working and the other is still missing in HOOBS/Homebridge and missing from "Device Data sent to Homebridge"

**Comment by con40** [comment]
@spud does your device that is missing in HomeKit show up in the HOOBS/Homebridge logs?  My device does (only in the logs, no where else) even though its missing from "View Device Data Sent to Homebridge".

**Comment by con40** [comment]
Linked [issue](https://github.com/hoobs-org/HOOBS/issues/1418).  Created since I see the missing device in the logs in HOOBS this may be (for me) a bug in HOOBS and not the Hubitat integration.
