### ISSUE TITLE
Manual events are not reporting

### ISSUE THREAD

**Issue by chaselampley** [tonesto7/homebridge-hubitat-tonesto7#95]
Bridge is working as expected and button pushes/switches react instantly. 

If a switch or button is operated within the Habitat ecosystem (ex: switch turned on or off, door unlocked, garage opened, sensor activated) this is not reflected in Hoobs or in Homekit. 

This was all working fine until I upgraded to Hoobs 4.0.79 and I deleted everything and started fresh. 

Hoobs: 4.0.79
Hoobs Hubitat Tonesto7 app 2.5.8
Homebridge v2 app v2.5.8

I was using an older version before and using the Maker API for my previous connection.

**Comment by knedd** [comment]
I was having a similar issue, which I solved by removing the optional Direct IP address and Direct Port parameters for the Hubitat Hub.  The IP address is already provided in the "app_url_local" parameter.  Including the Direct IP and Direct Port caused a conflict with the Hubitat Hub communicating with Homebridge-Hubitat plugin.
