### ISSUE TITLE
Zigbee plugs not recognized as accessories even though they show up in event log when turned on/off

### ISSUE THREAD

**Issue by herod05** [tonesto7/homebridge-hubitat-tonesto7#97]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [?  (installed via pkg mngr, not sure how to check ] That _OAuth_ is Enabled for the Hubitat App under the Homebridge v2 App under `App Code`.
-  [ X] The Hubitat App and Homebridge Plugin are updated to the latest code available.

---
## About Your Setup
-  How many devices are detected?: 14
-  Hubitat App Version: v2
-  Homebridge Plugin Version: 2.5.8
-  Homebridge Version: 2.5.8
-  NodeJS Version:12.18.2

## Expected Behavior
Homebridge should recognize as accessories Zigbee plugs that are controlled by Hubitat

## Current Behavior
Zigbee plugs do not show up as accessories in Homebridge (and then HomeKit), even though the event log tracks when I use Hubitat to turn them on or off. 

## Context
**How has this issue affected you? What are you trying to accomplish? Trying to control the plugs in HomeKit.
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

[7/15/2021, 10:00:40 AM] [Hubitat-v2] INFO: Your plugin version is up-to-date
[7/15/2021, 10:00:40 AM] [Hubitat-v2] Sending Plugin Status to Hubitat | UpdateAvailable: false | newVersion: 2.5.8
[7/15/2021, 10:01:08 AM] [Hubitat-v2] [Device Event]: (Office Lamp) [SWITCH] is off
[7/15/2021, 10:15:50 AM] [Hubitat-v2] [Device Event]: (Breakfast Table Lamp) [SWITCH] is on
[7/15/2021, 10:16:01 AM] [Hubitat-v2] [Device Event]: (Breakfast Table Lamp) [SWITCH] is off
![image](https://user-images.githubusercontent.com/87097872/125803596-5c812ae3-8aa6-43e3-9b11-1f586ae5fb0b.png)

**Comment by herod05** [comment]
Solved on my own (re-installed all the Zigbee devices).

**Comment by tonesto7** [comment]
I've never witnessed this issue before, but glad you got it working

**Comment by herod05** [comment]
Yup. I have no theories either, but don’t care—it’s working!

On to the next project…


From: tonesto7 ***@***.***>
Date: Thursday, July 15, 2021 at 3:54 PM
To: tonesto7/homebridge-hubitat-tonesto7 ***@***.***>
Cc: herod05 ***@***.***>, State change ***@***.***>
Subject: Re: [tonesto7/homebridge-hubitat-tonesto7] Zigbee plugs not recognized as accessories even though they show up in event log when turned on/off (#97)

I've never witnessed this issue before, but glad you got it working
