### ISSUE TITLE
(BUG) Missing color.png and water.png icon

### ISSUE THREAD

**Issue by jtp10181** [tonesto7/homebridge-hubitat-tonesto7#99]
## About Your Setup
-  How many devices are detected?: 25
-  Hubitat App Version: 2.5.8
-  Homebridge Plugin Version: 2.5.8
-  Homebridge Version:  1.3.4
-  NodeJS Version: 14.17.3

## Expected Behavior
Icon to all work

## Current Behavior
https://raw.githubusercontent.com/tonesto7/homebridge-hubitat-tonesto7/master/images/color.png
https://raw.githubusercontent.com/tonesto7/homebridge-hubitat-tonesto7/master/images/water.png

![image](https://user-images.githubusercontent.com/99599/126020993-99698d28-15f0-43ef-99bd-bef35ecd628e.png)

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

![image](https://user-images.githubusercontent.com/99599/126021012-4a8fb910-8ef6-4dcc-8561-a44b45993eee.png)

**Comment by tonesto7** [comment]
Thanks for reminding me to fix this has been resolved in v2.5.9
